/*	Benjamin DELPY `gentilkiwi`
	https://blog.gentilkiwi.com
	benjamin@gentilkiwi.com
	Licence : https://creativecommons.org/licenses/by/4.0/
*/
#include "jedec_manufacturers.h"

const char* JEDEC_BANKS_MANUFACTURERS[17][126] = {
	{ // bank #1
		{/*   1, 0x01, */ "AMD"},
		{/*   2, 0x02, */ "AMI" },
		{/*   3, 0x83, */ "Fairchild" },
		{/*   4, 0x04, */ "Fujitsu" },
		{/*   5, 0x85, */ "GTE" },
		{/*   6, 0x86, */ "Harris" },
		{/*   7, 0x07, */ "Hitachi" },
		{/*   8, 0x08, */ "Inmos" },
		{/*   9, 0x89, */ "Intel" },
		{/*  10, 0x8A, */ "I.T.T." },
		{/*  11, 0x0B, */ "Intersil" },
		{/*  12, 0x8C, */ "Monolithic Memories" },
		{/*  13, 0x0D, */ "Mostek" },
		{/*  14, 0x0E, */ "Freescale (Motorola)" },
		{/*  15, 0x8F, */ "National" },
		{/*  16, 0x10, */ "NEC" },
		{/*  17, 0x91, */ "RCA" },
		{/*  18, 0x92, */ "Raytheon" },
		{/*  19, 0x13, */ "Synaptics" },
		{/*  20, 0x94, */ "Seeq" },
		{/*  21, 0x15, */ "NXP (Philips)" },
		{/*  22, 0x16, */ "Synertek" },
		{/*  23, 0x97, */ "Texas Instruments" },
		{/*  24, 0x98, */ "Kioxia Corporation" },
		{/*  25, 0x19, */ "Xicor" },
		{/*  26, 0x1A, */ "Zilog" },
		{/*  27, 0x9B, */ "Eurotechnique" },
		{/*  28, 0x1C, */ "Mitsubishi" },
		{/*  29, 0x9D, */ "Lucent (AT&T)" },
		{/*  30, 0x9E, */ "Exel" },
		{/*  31, 0x1F, */ "Atmel" },
		{/*  32, 0x20, */ "STMicroelectronics" },
		{/*  33, 0xA1, */ "Lattice Semi." },
		{/*  34, 0xA2, */ "NCR" },
		{/*  35, 0x23, */ "Wafer Scale Integration" },
		{/*  36, 0xA4, */ "IBM" },
		{/*  37, 0x25, */ "Tristar" },
		{/*  38, 0x26, */ "Visic" },
		{/*  39, 0xA7, */ "Intl. CMOS Technology" },
		{/*  40, 0xA8, */ "SSSI" },
		{/*  41, 0x29, */ "Microchip Technology" },
		{/*  42, 0x2A, */ "Ricoh Ltd" },
		{/*  43, 0xAB, */ "VLSI" },
		{/*  44, 0x2C, */ "Micron Technology" },
		{/*  45, 0xAD, */ "SK Hynix" },
		{/*  46, 0xAE, */ "OKI Semiconductor" },
		{/*  47, 0x2F, */ "ACTEL" },
		{/*  48, 0xB0, */ "Sharp" },
		{/*  49, 0x31, */ "Catalyst" },
		{/*  50, 0x32, */ "Panasonic" },
		{/*  51, 0xB3, */ "IDT" },
		{/*  52, 0x34, */ "Cypress" },
		{/*  53, 0xB5, */ "DEC" },
		{/*  54, 0xB6, */ "LSI Logic" },
		{/*  55, 0x37, */ "Zarlink (Plessey)" },
		{/*  56, 0x38, */ "UTMC" },
		{/*  57, 0xB9, */ "Thinking Machine" },
		{/*  58, 0xBA, */ "Thomson CSF" },
		{/*  59, 0x3B, */ "Integrated CMOS (Vertex)" },
		{/*  60, 0xBC, */ "Honeywell" },
		{/*  61, 0x3D, */ "Tektronix" },
		{/*  62, 0x3E, */ "Oracle Corporation" },
		{/*  63, 0xBF, */ "Silicon Storage Technology" },
		{/*  64, 0x40, */ "ProMos/Mosel Vitelic" },
		{/*  65, 0xC1, */ "Infineon (Siemens)" },
		{/*  66, 0xC2, */ "Macronix" },
		{/*  67, 0x43, */ "Xerox" },
		{/*  68, 0xC4, */ "Plus Logic" },
		{/*  69, 0x45, */ "Western Digital Technologies Inc" },
		{/*  70, 0x46, */ "Elan Circuit Tech." },
		{/*  71, 0xC7, */ "European Silicon Str." },
		{/*  72, 0xC8, */ "Apple Computer" },
		{/*  73, 0x49, */ "Xilinx" },
		{/*  74, 0x4A, */ "Compaq" },
		{/*  75, 0xCB, */ "Protocol Engines" },
		{/*  76, 0x4C, */ "SCI" },
		{/*  77, 0xCD, */ "ABLIC" },
		{/*  78, 0xCE, */ "Samsung" },
		{/*  79, 0x4F, */ "I3 Design System" },
		{/*  80, 0xD0, */ "Klic" },
		{/*  81, 0x51, */ "Crosspoint Solutions" },
		{/*  82, 0x52, */ "Alliance Memory Inc" },
		{/*  83, 0xD3, */ "Tandem" },
		{/*  84, 0x54, */ "Hewlett-Packard" },
		{/*  85, 0xD5, */ "Integrated Silicon Solutions" },
		{/*  86, 0xD6, */ "Brooktree" },
		{/*  87, 0x57, */ "New Media" },
		{/*  88, 0x58, */ "MHS Electronic" },
		{/*  89, 0xD9, */ "Performance Semi." },
		{/*  90, 0xDA, */ "Winbond Electronic" },
		{/*  91, 0x5B, */ "Kawasaki Steel" },
		{/*  92, 0xDC, */ "Bright Micro" },
		{/*  93, 0x5D, */ "TECMAR" },
		{/*  94, 0x5E, */ "Exar" },
		{/*  95, 0xDF, */ "PCMCIA" },
		{/*  96, 0xE0, */ "LG Semi (Goldstar)" },
		{/*  97, 0x61, */ "Northern Telecom" },
		{/*  98, 0x62, */ "Sanyo" },
		{/*  99, 0xE3, */ "Array Microsystems" },
		{/* 100, 0x64, */ "Crystal Semiconductor" },
		{/* 101, 0xE5, */ "Analog Devices" },
		{/* 102, 0xE6, */ "PMC-Sierra" },
		{/* 103, 0x67, */ "Asparix" },
		{/* 104, 0x68, */ "Convex Computer" },
		{/* 105, 0xE9, */ "Quality Semiconductor" },
		{/* 106, 0xEA, */ "Nimbus Technology" },
		{/* 107, 0x6B, */ "Transwitch" },
		{/* 108, 0xEC, */ "Micronas (ITT Intermetall)" },
		{/* 109, 0x6D, */ "Cannon" },
		{/* 110, 0x6E, */ "Altera" },
		{/* 111, 0xEF, */ "NEXCOM" },
		{/* 112, 0x70, */ "Qualcomm" },
		{/* 113, 0xF1, */ "Sony" },
		{/* 114, 0xF2, */ "Cray Research" },
		{/* 115, 0x73, */ "AMS(Austria Micro)" },
		{/* 116, 0xF4, */ "Vitesse" },
		{/* 117, 0x75, */ "Aster Electronics" },
		{/* 118, 0x76, */ "Bay Networks (Synoptic)" },
		{/* 119, 0xF7, */ "Zentrum/ZMD" },
		{/* 120, 0xF8, */ "TRW" },
		{/* 121, 0x79, */ "Thesys" },
		{/* 122, 0x7A, */ "Solbourne Computer" },
		{/* 123, 0xFB, */ "Allied-Signal" },
		{/* 124, 0x7C, */ "Dialog Semiconductor" },
		{/* 125, 0xFD, */ "Media Vision" },
		{/* 126, 0xFE, */ "Numonyx Corporation" },
	},
	{ // bank #2
		{/*   1, 0x01, */ "Cirrus Logic"},
		{/*   2, 0x02, */ "National Instruments"},
		{/*   3, 0x83, */ "ILC Data Device"},
		{/*   4, 0x04, */ "Alcatel Mietec"},
		{/*   5, 0x85, */ "Micro Linear"},
		{/*   6, 0x86, */ "Univ. of NC"},
		{/*   7, 0x07, */ "JTAG Technologies"},
		{/*   8, 0x08, */ "BAE Systems (Loral)"},
		{/*   9, 0x89, */ "Nchip"},
		{/*  10, 0x8A, */ "Galileo Tech"},
		{/*  11, 0x0B, */ "Bestlink Systems"},
		{/*  12, 0x8C, */ "Graychip"},
		{/*  13, 0x0D, */ "GENNUM"},
		{/*  14, 0x0E, */ "Imagination Technologies Limited"},
		{/*  15, 0x8F, */ "Robert Bosch"},
		{/*  16, 0x10, */ "Chip Express"},
		{/*  17, 0x91, */ "DATARAM"},
		{/*  18, 0x92, */ "United Microelectronics Corp"},
		{/*  19, 0x13, */ "TCSI"},
		{/*  20, 0x94, */ "Smart Modular"},
		{/*  21, 0x15, */ "Hughes Aircraft"},
		{/*  22, 0x16, */ "Lanstar Semiconductor"},
		{/*  23, 0x97, */ "Qlogic"},
		{/*  24, 0x98, */ "Kingston"},
		{/*  25, 0x19, */ "Music Semi"},
		{/*  26, 0x1A, */ "Ericsson Components"},
		{/*  27, 0x9B, */ "SpaSE"},
		{/*  28, 0x1C, */ "Eon Silicon Devices"},
		{/*  29, 0x9D, */ "Integrated Silicon Solution (ISSI)"},
		{/*  30, 0x9E, */ "DoD"},
		{/*  31, 0x1F, */ "Integ. Memories Tech."},
		{/*  32, 0x20, */ "Corollary Inc"},
		{/*  33, 0xA1, */ "Dallas Semiconductor"},
		{/*  34, 0xA2, */ "Omnivision"},
		{/*  35, 0x23, */ "EIV(Switzerland)"},
		{/*  36, 0xA4, */ "Novatel Wireless"},
		{/*  37, 0x25, */ "Zarlink (Mitel)"},
		{/*  38, 0x26, */ "Clearpoint"},
		{/*  39, 0xA7, */ "Cabletron"},
		{/*  40, 0xA8, */ "STEC (Silicon Tech)"},
		{/*  41, 0x29, */ "Vanguard"},
		{/*  42, 0x2A, */ "Hagiwara Solutions Co Ltd"},
		{/*  43, 0xAB, */ "Vantis"},
		{/*  44, 0x2C, */ "Celestica"},
		{/*  45, 0xAD, */ "Century"},
		{/*  46, 0xAE, */ "Hal Computers"},
		{/*  47, 0x2F, */ "Rohm Company Ltd"},
		{/*  48, 0xB0, */ "Juniper Networks"},
		{/*  49, 0x31, */ "Libit Signal Processing"},
		{/*  50, 0x32, */ "Mushkin Enhanced Memory"},
		{/*  51, 0xB3, */ "Tundra Semiconductor"},
		{/*  52, 0x34, */ "Adaptec Inc"},
		{/*  53, 0xB5, */ "LightSpeed Semi."},
		{/*  54, 0xB6, */ "ZSP Corp"},
		{/*  55, 0x37, */ "AMIC Technology"},
		{/*  56, 0x38, */ "Adobe Systems"},
		{/*  57, 0xB9, */ "Dynachip"},
		{/*  58, 0xBA, */ "PNY Technologies Inc"},
		{/*  59, 0x3B, */ "Newport Digital"},
		{/*  60, 0xBC, */ "MMC Networks"},
		{/*  61, 0x3D, */ "T Square"},
		{/*  62, 0x3E, */ "Seiko Epson"},
		{/*  63, 0xBF, */ "Broadcom"},
		{/*  64, 0x40, */ "Viking Components"},
		{/*  65, 0xC1, */ "V3 Semiconductor"},
		{/*  66, 0xC2, */ "Flextronics (Orbit Semiconductor)"},
		{/*  67, 0x43, */ "Suwa Electronics"},
		{/*  68, 0xC4, */ "Transmeta"},
		{/*  69, 0x45, */ "Micron CMS"},
		{/*  70, 0x46, */ "American Computer & Digital Components Inc"},
		{/*  71, 0xC7, */ "Enhance 3000 Inc"},
		{/*  72, 0xC8, */ "Tower Semiconductor"},
		{/*  73, 0x49, */ "CPU Design"},
		{/*  74, 0x4A, */ "Price Point"},
		{/*  75, 0xCB, */ "Maxim Integrated Product"},
		{/*  76, 0x4C, */ "Tellabs"},
		{/*  77, 0xCD, */ "Centaur Technology"},
		{/*  78, 0xCE, */ "Unigen Corporation"},
		{/*  79, 0x4F, */ "Transcend Information"},
		{/*  80, 0xD0, */ "Memory Card Technology"},
		{/*  81, 0x51, */ "CKD Corporation Ltd"},
		{/*  82, 0x52, */ "Capital Instruments Inc"},
		{/*  83, 0xD3, */ "Aica Kogyo Ltd"},
		{/*  84, 0x54, */ "Linvex Technology"},
		{/*  85, 0xD5, */ "MSC Vertriebs GmbH"},
		{/*  86, 0xD6, */ "AKM Company Ltd"},
		{/*  87, 0x57, */ "Dynamem Inc"},
		{/*  88, 0x58, */ "NERA ASA"},
		{/*  89, 0xD9, */ "GSI Technology"},
		{/*  90, 0xDA, */ "Dane-Elec (C Memory)"},
		{/*  91, 0x5B, */ "Acorn Computers"},
		{/*  92, 0xDC, */ "Lara Technology"},
		{/*  93, 0x5D, */ "Oak Technology Inc"},
		{/*  94, 0x5E, */ "Itec Memory"},
		{/*  95, 0xDF, */ "Tanisys Technology"},
		{/*  96, 0xE0, */ "Truevision"},
		{/*  97, 0x61, */ "Wintec Industries"},
		{/*  98, 0x62, */ "Super PC Memory"},
		{/*  99, 0xE3, */ "MGV Memory"},
		{/* 100, 0x64, */ "Galvantech"},
		{/* 101, 0xE5, */ "Gadzoox Networks"},
		{/* 102, 0xE6, */ "Multi Dimensional Cons."},
		{/* 103, 0x67, */ "GateField"},
		{/* 104, 0x68, */ "Integrated Memory System"},
		{/* 105, 0xE9, */ "Triscend"},
		{/* 106, 0xEA, */ "XaQti"},
		{/* 107, 0x6B, */ "Goldenram"},
		{/* 108, 0xEC, */ "Clear Logic"},
		{/* 109, 0x6D, */ "Cimaron Communications"},
		{/* 110, 0x6E, */ "Nippon Steel Semi. Corp"},
		{/* 111, 0xEF, */ "Advantage Memory"},
		{/* 112, 0x70, */ "AMCC"},
		{/* 113, 0xF1, */ "LeCroy"},
		{/* 114, 0xF2, */ "Yamaha Corporation"},
		{/* 115, 0x73, */ "Digital Microwave"},
		{/* 116, 0xF4, */ "NetLogic Microsystems"},
		{/* 117, 0x75, */ "MIMOS Semiconductor"},
		{/* 118, 0x76, */ "Advanced Fibre"},
		{/* 119, 0xF7, */ "BF Goodrich Data."},
		{/* 120, 0xF8, */ "Epigram"},
		{/* 121, 0x79, */ "Acbel Polytech Inc"},
		{/* 122, 0x7A, */ "Apacer Technology"},
		{/* 123, 0xFB, */ "Admor Memory"},
		{/* 124, 0x7C, */ "FOXCONN"},
		{/* 125, 0xFD, */ "Quadratics Superconductor"},
		{/* 126, 0xFE, */ "3COM"},
	},
	{ // bank #3
		{/*   1, 0x01, */ "Camintonn Corporation"},
		{/*   2, 0x02, */ "ISOA Incorporated"},
		{/*   3, 0x83, */ "Agate Semiconductor"},
		{/*   4, 0x04, */ "ADMtek Incorporated"},
		{/*   5, 0x85, */ "HYPERTEC"},
		{/*   6, 0x86, */ "Adhoc Technologies"},
		{/*   7, 0x07, */ "MOSAID Technologies"},
		{/*   8, 0x08, */ "Ardent Technologies"},
		{/*   9, 0x89, */ "Switchcore"},
		{/*  10, 0x8A, */ "Cisco Systems Inc"},
		{/*  11, 0x0B, */ "Allayer Technologies"},
		{/*  12, 0x8C, */ "WorkX AG (Wichman)"},
		{/*  13, 0x0D, */ "Oasis Semiconductor"},
		{/*  14, 0x0E, */ "Novanet Semiconductor"},
		{/*  15, 0x8F, */ "E-M Solutions"},
		{/*  16, 0x10, */ "Power General"},
		{/*  17, 0x91, */ "Advanced Hardware Arch."},
		{/*  18, 0x92, */ "Inova Semiconductors GmbH"},
		{/*  19, 0x13, */ "Telocity"},
		{/*  20, 0x94, */ "Delkin Devices"},
		{/*  21, 0x15, */ "Symagery Microsystems"},
		{/*  22, 0x16, */ "C-Port Corporation"},
		{/*  23, 0x97, */ "SiberCore Technologies"},
		{/*  24, 0x98, */ "Southland Microsystems"},
		{/*  25, 0x19, */ "Malleable Technologies"},
		{/*  26, 0x1A, */ "Kendin Communications"},
		{/*  27, 0x9B, */ "Great Technology Microcomputer"},
		{/*  28, 0x1C, */ "Sanmina Corporation"},
		{/*  29, 0x9D, */ "HADCO Corporation"},
		{/*  30, 0x9E, */ "Corsair"},
		{/*  31, 0x1F, */ "Actrans System Inc"},
		{/*  32, 0x20, */ "ALPHA Technologies"},
		{/*  33, 0xA1, */ "Silicon Laboratories Inc (Cygnal)"},
		{/*  34, 0xA2, */ "Artesyn Technologies"},
		{/*  35, 0x23, */ "Align Manufacturing"},
		{/*  36, 0xA4, */ "Peregrine Semiconductor"},
		{/*  37, 0x25, */ "Chameleon Systems"},
		{/*  38, 0x26, */ "Aplus Flash Technology"},
		{/*  39, 0xA7, */ "MIPS Technologies"},
		{/*  40, 0xA8, */ "Chrysalis ITS"},
		{/*  41, 0x29, */ "ADTEC Corporation"},
		{/*  42, 0x2A, */ "Kentron Technologies"},
		{/*  43, 0xAB, */ "Win Technologies"},
		{/*  44, 0x2C, */ "Tezzaron Semiconductor"},
		{/*  45, 0xAD, */ "Extreme Packet Devices"},
		{/*  46, 0xAE, */ "RF Micro Devices"},
		{/*  47, 0x2F, */ "Siemens AG"},
		{/*  48, 0xB0, */ "Sarnoff Corporation"},
		{/*  49, 0x31, */ "Itautec SA"},
		{/*  50, 0x32, */ "Radiata Inc"},
		{/*  51, 0xB3, */ "Benchmark Elect. (AVEX)"},
		{/*  52, 0x34, */ "Legend"},
		{/*  53, 0xB5, */ "SpecTek Incorporated"},
		{/*  54, 0xB6, */ "Hi/fn"},
		{/*  55, 0x37, */ "Enikia Incorporated"},
		{/*  56, 0x38, */ "SwitchOn Networks"},
		{/*  57, 0xB9, */ "AANetcom Incorporated"},
		{/*  58, 0xBA, */ "Micro Memory Bank"},
		{/*  59, 0x3B, */ "ESS Technology"},
		{/*  60, 0xBC, */ "Virata Corporation"},
		{/*  61, 0x3D, */ "Excess Bandwidth"},
		{/*  62, 0x3E, */ "West Bay Semiconductor"},
		{/*  63, 0xBF, */ "DSP Group"},
		{/*  64, 0x40, */ "Newport Communications"},
		{/*  65, 0xC1, */ "Chip2Chip Incorporated"},
		{/*  66, 0xC2, */ "Phobos Corporation"},
		{/*  67, 0x43, */ "Intellitech Corporation"},
		{/*  68, 0xC4, */ "Nordic VLSI ASA"},
		{/*  69, 0x45, */ "Ishoni Networks"},
		{/*  70, 0x46, */ "Silicon Spice"},
		{/*  71, 0xC7, */ "Alchemy Semiconductor"},
		{/*  72, 0xC8, */ "Agilent Technologies"},
		{/*  73, 0x49, */ "Centillium Communications"},
		{/*  74, 0x4A, */ "W.L. Gore"},
		{/*  75, 0xCB, */ "HanBit Electronics"},
		{/*  76, 0x4C, */ "GlobeSpan"},
		{/*  77, 0xCD, */ "Element 14"},
		{/*  78, 0xCE, */ "Pycon"},
		{/*  79, 0x4F, */ "Saifun Semiconductors"},
		{/*  80, 0xD0, */ "Sibyte Incorporated"},
		{/*  81, 0x51, */ "MetaLink Technologies"},
		{/*  82, 0x52, */ "Feiya Technology"},
		{/*  83, 0xD3, */ "I & C Technology"},
		{/*  84, 0x54, */ "Shikatronics"},
		{/*  85, 0xD5, */ "Elektrobit"},
		{/*  86, 0xD6, */ "Megic"},
		{/*  87, 0x57, */ "Com-Tier"},
		{/*  88, 0x58, */ "Malaysia Micro Solutions"},
		{/*  89, 0xD9, */ "Hyperchip"},
		{/*  90, 0xDA, */ "Gemstone Communications"},
		{/*  91, 0x5B, */ "Anadigm (Anadyne)"},
		{/*  92, 0xDC, */ "3ParData"},
		{/*  93, 0x5D, */ "Mellanox Technologies"},
		{/*  94, 0x5E, */ "Tenx Technologies"},
		{/*  95, 0xDF, */ "Helix AG"},
		{/*  96, 0xE0, */ "Domosys"},
		{/*  97, 0x61, */ "Skyup Technology"},
		{/*  98, 0x62, */ "HiNT Corporation"},
		{/*  99, 0xE3, */ "Chiaro"},
		{/* 100, 0x64, */ "MDT Technologies GmbH"},
		{/* 101, 0xE5, */ "Exbit Technology A/S"},
		{/* 102, 0xE6, */ "Integrated Technology Express"},
		{/* 103, 0x67, */ "AVED Memory"},
		{/* 104, 0x68, */ "Legerity"},
		{/* 105, 0xE9, */ "Jasmine Networks"},
		{/* 106, 0xEA, */ "Caspian Networks"},
		{/* 107, 0x6B, */ "nCUBE"},
		{/* 108, 0xEC, */ "Silicon Access Networks"},
		{/* 109, 0x6D, */ "FDK Corporation"},
		{/* 110, 0x6E, */ "High Bandwidth Access"},
		{/* 111, 0xEF, */ "MultiLink Technology"},
		{/* 112, 0x70, */ "BRECIS"},
		{/* 113, 0xF1, */ "World Wide Packets"},
		{/* 114, 0xF2, */ "APW"},
		{/* 115, 0x73, */ "Chicory Systems"},
		{/* 116, 0xF4, */ "Xstream Logic"},
		{/* 117, 0x75, */ "Fast-Chip"},
		{/* 118, 0x76, */ "Zucotto Wireless"},
		{/* 119, 0xF7, */ "Realchip"},
		{/* 120, 0xF8, */ "Galaxy Power"},
		{/* 121, 0x79, */ "eSilicon"},
		{/* 122, 0x7A, */ "Morphics Technology"},
		{/* 123, 0xFB, */ "Accelerant Networks"},
		{/* 124, 0x7C, */ "Silicon Wave"},
		{/* 125, 0xFD, */ "SandCraft"},
		{/* 126, 0xFE, */ "Elpida"},
	},
	{ // bank #4
		{/*   1, 0x01, */ "Solectron"},
		{/*   2, 0x02, */ "Optosys Technologies"},
		{/*   3, 0x83, */ "Buffalo (Formerly Melco)"},
		{/*   4, 0x04, */ "TriMedia Technologies"},
		{/*   5, 0x85, */ "Cyan Technologies"},
		{/*   6, 0x86, */ "Global Locate"},
		{/*   7, 0x07, */ "Optillion"},
		{/*   8, 0x08, */ "Terago Communications"},
		{/*   9, 0x89, */ "Ikanos Communications"},
		{/*  10, 0x8A, */ "Princeton Technology"},
		{/*  11, 0x0B, */ "Nanya Technology"},
		{/*  12, 0x8C, */ "Elite Flash Storage"},
		{/*  13, 0x0D, */ "Mysticom"},
		{/*  14, 0x0E, */ "LightSand Communications"},
		{/*  15, 0x8F, */ "ATI Technologies"},
		{/*  16, 0x10, */ "Agere Systems"},
		{/*  17, 0x91, */ "NeoMagic"},
		{/*  18, 0x92, */ "AuroraNetics"},
		{/*  19, 0x13, */ "Golden Empire"},
		{/*  20, 0x94, */ "Mushkin"},
		{/*  21, 0x15, */ "Tioga Technologies"},
		{/*  22, 0x16, */ "Netlist"},
		{/*  23, 0x97, */ "TeraLogic"},
		{/*  24, 0x98, */ "Cicada Semiconductor"},
		{/*  25, 0x19, */ "Centon Electronics"},
		{/*  26, 0x1A, */ "Tyco Electronics"},
		{/*  27, 0x9B, */ "Magis Works"},
		{/*  28, 0x1C, */ "Zettacom"},
		{/*  29, 0x9D, */ "Cogency Semiconductor"},
		{/*  30, 0x9E, */ "Chipcon AS"},
		{/*  31, 0x1F, */ "Aspex Technology"},
		{/*  32, 0x20, */ "F5 Networks"},
		{/*  33, 0xA1, */ "Programmable Silicon Solutions"},
		{/*  34, 0xA2, */ "ChipWrights"},
		{/*  35, 0x23, */ "Acorn Networks"},
		{/*  36, 0xA4, */ "Quicklogic"},
		{/*  37, 0x25, */ "Kingmax Semiconductor"},
		{/*  38, 0x26, */ "BOPS"},
		{/*  39, 0xA7, */ "Flasys"},
		{/*  40, 0xA8, */ "BitBlitz Communications"},
		{/*  41, 0x29, */ "eMemory Technology"},
		{/*  42, 0x2A, */ "Procket Networks"},
		{/*  43, 0xAB, */ "Purple Ray"},
		{/*  44, 0x2C, */ "Trebia Networks"},
		{/*  45, 0xAD, */ "Delta Electronics"},
		{/*  46, 0xAE, */ "Onex Communications"},
		{/*  47, 0x2F, */ "Ample Communications"},
		{/*  48, 0xB0, */ "Memory Experts Intl"},
		{/*  49, 0x31, */ "Astute Networks"},
		{/*  50, 0x32, */ "Azanda Network Devices"},
		{/*  51, 0xB3, */ "Dibcom"},
		{/*  52, 0x34, */ "Tekmos"},
		{/*  53, 0xB5, */ "API NetWorks"},
		{/*  54, 0xB6, */ "Bay Microsystems"},
		{/*  55, 0x37, */ "Firecron Ltd"},
		{/*  56, 0x38, */ "Resonext Communications"},
		{/*  57, 0xB9, */ "Tachys Technologies"},
		{/*  58, 0xBA, */ "Equator Technology"},
		{/*  59, 0x3B, */ "Concept Computer"},
		{/*  60, 0xBC, */ "SILCOM"},
		{/*  61, 0x3D, */ "3Dlabs"},
		{/*  62, 0x3E, */ "c’t Magazine"},
		{/*  63, 0xBF, */ "Sanera Systems"},
		{/*  64, 0x40, */ "Silicon Packets"},
		{/*  65, 0xC1, */ "Viasystems Group"},
		{/*  66, 0xC2, */ "Simtek"},
		{/*  67, 0x43, */ "Semicon Devices Singapore"},
		{/*  68, 0xC4, */ "Satron Handelsges"},
		{/*  69, 0x45, */ "Improv Systems"},
		{/*  70, 0x46, */ "INDUSYS GmbH"},
		{/*  71, 0xC7, */ "Corrent"},
		{/*  72, 0xC8, */ "Infrant Technologies"},
		{/*  73, 0x49, */ "Ritek Corp"},
		{/*  74, 0x4A, */ "empowerTel Networks"},
		{/*  75, 0xCB, */ "Hypertec"},
		{/*  76, 0x4C, */ "Cavium Networks"},
		{/*  77, 0xCD, */ "PLX Technology"},
		{/*  78, 0xCE, */ "Massana Design"},
		{/*  79, 0x4F, */ "Intrinsity"},
		{/*  80, 0xD0, */ "Valence Semiconductor"},
		{/*  81, 0x51, */ "Terawave Communications"},
		{/*  82, 0x52, */ "IceFyre Semiconductor"},
		{/*  83, 0xD3, */ "Primarion"},
		{/*  84, 0x54, */ "Picochip Designs Ltd"},
		{/*  85, 0xD5, */ "Silverback Systems"},
		{/*  86, 0xD6, */ "Jade Star Technologies"},
		{/*  87, 0x57, */ "Pijnenburg Securealink"},
		{/*  88, 0x58, */ "takeMS - Ultron AG"},
		{/*  89, 0xD9, */ "Cambridge Silicon Radio"},
		{/*  90, 0xDA, */ "Swissbit"},
		{/*  91, 0x5B, */ "Nazomi Communications"},
		{/*  92, 0xDC, */ "eWave System"},
		{/*  93, 0x5D, */ "Rockwell Collins"},
		{/*  94, 0x5E, */ "Picocel Co Ltd (Paion)"},
		{/*  95, 0xDF, */ "Alphamosaic Ltd"},
		{/*  96, 0xE0, */ "Sandburst"},
		{/*  97, 0x61, */ "SiCon Video"},
		{/*  98, 0x62, */ "NanoAmp Solutions"},
		{/*  99, 0xE3, */ "Ericsson Technology"},
		{/* 100, 0x64, */ "PrairieComm"},
		{/* 101, 0xE5, */ "Mitac International"},
		{/* 102, 0xE6, */ "Layer N Networks"},
		{/* 103, 0x67, */ "MtekVision (Atsana)"},
		{/* 104, 0x68, */ "Allegro Networks"},
		{/* 105, 0xE9, */ "Marvell Semiconductors"},
		{/* 106, 0xEA, */ "Netergy Microelectronic"},
		{/* 107, 0x6B, */ "NVIDIA"},
		{/* 108, 0xEC, */ "Internet Machines"},
		{/* 109, 0x6D, */ "Memorysolution GmbH"},
		{/* 110, 0x6E, */ "Litchfield Communication"},
		{/* 111, 0xEF, */ "Accton Technology"},
		{/* 112, 0x70, */ "Teradiant Networks"},
		{/* 113, 0xF1, */ "Scaleo Chip"},
		{/* 114, 0xF2, */ "Cortina Systems"},
		{/* 115, 0x73, */ "RAM Components"},
		{/* 116, 0xF4, */ "Raqia Networks"},
		{/* 117, 0x75, */ "ClearSpeed"},
		{/* 118, 0x76, */ "Matsushita Battery"},
		{/* 119, 0xF7, */ "Xelerated"},
		{/* 120, 0xF8, */ "SimpleTech"},
		{/* 121, 0x79, */ "Utron Technology"},
		{/* 122, 0x7A, */ "Astec International"},
		{/* 123, 0xFB, */ "AVM gmbH"},
		{/* 124, 0x7C, */ "Redux Communications"},
		{/* 125, 0xFD, */ "Dot Hill Systems"},
		{/* 126, 0xFE, */ "TeraChip"},
	},
	{ // bank #5
		{/*   1, 0x01, */ "T-RAM Incorporated"},
		{/*   2, 0x02, */ "Innovics Wireless"},
		{/*   3, 0x83, */ "Teknovus"},
		{/*   4, 0x04, */ "KeyEye Communications"},
		{/*   5, 0x85, */ "Runcom Technologies"},
		{/*   6, 0x86, */ "RedSwitch"},
		{/*   7, 0x07, */ "Dotcast"},
		{/*   8, 0x08, */ "Silicon Mountain Memory"},
		{/*   9, 0x89, */ "Signia Technologies"},
		{/*  10, 0x8A, */ "Pixim"},
		{/*  11, 0x0B, */ "Galazar Networks"},
		{/*  12, 0x8C, */ "White Electronic Designs"},
		{/*  13, 0x0D, */ "Patriot Scientific"},
		{/*  14, 0x0E, */ "Neoaxiom Corporation"},
		{/*  15, 0x8F, */ "3Y Power Technology"},
		{/*  16, 0x10, */ "Scaleo Chip"},
		{/*  17, 0x91, */ "Potentia Power Systems"},
		{/*  18, 0x92, */ "C-guys Incorporated"},
		{/*  19, 0x13, */ "Digital Communications Technology Inc"},
		{/*  20, 0x94, */ "Silicon-Based Technology"},
		{/*  21, 0x15, */ "Fulcrum Microsystems"},
		{/*  22, 0x16, */ "Positivo Informatica Ltd"},
		{/*  23, 0x97, */ "XIOtech Corporation"},
		{/*  24, 0x98, */ "PortalPlayer"},
		{/*  25, 0x19, */ "Zhiying Software"},
		{/*  26, 0x1A, */ "ParkerVision Inc"},
		{/*  27, 0x9B, */ "Phonex Broadband"},
		{/*  28, 0x1C, */ "Skyworks Solutions"},
		{/*  29, 0x9D, */ "Entropic Communications"},
		{/*  30, 0x9E, */ "I’M Intelligent Memory Ltd"},
		{/*  31, 0x1F, */ "Zensys A/S"},
		{/*  32, 0x20, */ "Legend Silicon Corp"},
		{/*  33, 0xA1, */ "Sci-worx GmbH"},
		{/*  34, 0xA2, */ "SMSC (Standard Microsystems)"},
		{/*  35, 0x23, */ "Renesas Electronics"},
		{/*  36, 0xA4, */ "Raza Microelectronics"},
		{/*  37, 0x25, */ "Phyworks"},
		{/*  38, 0x26, */ "MediaTek"},
		{/*  39, 0xA7, */ "Non-cents Productions"},
		{/*  40, 0xA8, */ "US Modular"},
		{/*  41, 0x29, */ "Wintegra Ltd"},
		{/*  42, 0x2A, */ "Mathstar"},
		{/*  43, 0xAB, */ "StarCore"},
		{/*  44, 0x2C, */ "Oplus Technologies"},
		{/*  45, 0xAD, */ "Mindspeed"},
		{/*  46, 0xAE, */ "Just Young Computer"},
		{/*  47, 0x2F, */ "Radia Communications"},
		{/*  48, 0xB0, */ "OCZ"},
		{/*  49, 0x31, */ "Emuzed"},
		{/*  50, 0x32, */ "LOGIC Devices"},
		{/*  51, 0xB3, */ "Inphi Corporation"},
		{/*  52, 0x34, */ "Quake Technologies"},
		{/*  53, 0xB5, */ "Vixel"},
		{/*  54, 0xB6, */ "SolusTek"},
		{/*  55, 0x37, */ "Kongsberg Maritime"},
		{/*  56, 0x38, */ "Faraday Technology"},
		{/*  57, 0xB9, */ "Altium Ltd"},
		{/*  58, 0xBA, */ "Insyte"},
		{/*  59, 0x3B, */ "ARM Ltd"},
		{/*  60, 0xBC, */ "DigiVision"},
		{/*  61, 0x3D, */ "Vativ Technologies"},
		{/*  62, 0x3E, */ "Endicott Interconnect Technologies"},
		{/*  63, 0xBF, */ "Pericom"},
		{/*  64, 0x40, */ "Bandspeed"},
		{/*  65, 0xC1, */ "LeWiz Communications"},
		{/*  66, 0xC2, */ "CPU Technology"},
		{/*  67, 0x43, */ "Ramaxel Technology"},
		{/*  68, 0xC4, */ "DSP Group"},
		{/*  69, 0x45, */ "Axis Communications"},
		{/*  70, 0x46, */ "Legacy Electronics"},
		{/*  71, 0xC7, */ "Chrontel"},
		{/*  72, 0xC8, */ "Powerchip Semiconductor"},
		{/*  73, 0x49, */ "MobilEye Technologies"},
		{/*  74, 0x4A, */ "Excel Semiconductor"},
		{/*  75, 0xCB, */ "A-DATA Technology"},
		{/*  76, 0x4C, */ "VirtualDigm"},
		{/*  77, 0xCD, */ "G Skill Intl"},
		{/*  78, 0xCE, */ "Quanta Computer"},
		{/*  79, 0x4F, */ "Yield Microelectronics"},
		{/*  80, 0xD0, */ "Afa Technologies"},
		{/*  81, 0x51, */ "KINGBOX Technology Co Ltd"},
		{/*  82, 0x52, */ "Ceva"},
		{/*  83, 0xD3, */ "iStor Networks"},
		{/*  84, 0x54, */ "Advance Modules"},
		{/*  85, 0xD5, */ "Microsoft"},
		{/*  86, 0xD6, */ "Open-Silicon"},
		{/*  87, 0x57, */ "Goal Semiconductor"},
		{/*  88, 0x58, */ "ARC International"},
		{/*  89, 0xD9, */ "Simmtec"},
		{/*  90, 0xDA, */ "Metanoia"},
		{/*  91, 0x5B, */ "Key Stream"},
		{/*  92, 0xDC, */ "Lowrance Electronics"},
		{/*  93, 0x5D, */ "Adimos"},
		{/*  94, 0x5E, */ "SiGe Semiconductor"},
		{/*  95, 0xDF, */ "Fodus Communications"},
		{/*  96, 0xE0, */ "Credence Systems Corp"},
		{/*  97, 0x61, */ "Genesis Microchip Inc"},
		{/*  98, 0x62, */ "Vihana Inc"},
		{/*  99, 0xE3, */ "WIS Technologies"},
		{/* 100, 0x64, */ "GateChange Technologies"},
		{/* 101, 0xE5, */ "High Density Devices AS"},
		{/* 102, 0xE6, */ "Synopsys"},
		{/* 103, 0x67, */ "Gigaram"},
		{/* 104, 0x68, */ "Enigma Semiconductor Inc"},
		{/* 105, 0xE9, */ "Century Micro Inc"},
		{/* 106, 0xEA, */ "Icera Semiconductor"},
		{/* 107, 0x6B, */ "Mediaworks Integrated Systems"},
		{/* 108, 0xEC, */ "O’Neil Product Development"},
		{/* 109, 0x6D, */ "Supreme Top Technology Ltd"},
		{/* 110, 0x6E, */ "MicroDisplay Corporation"},
		{/* 111, 0xEF, */ "Team Group Inc"},
		{/* 112, 0x70, */ "Sinett Corporation"},
		{/* 113, 0xF1, */ "Toshiba Corporation"},
		{/* 114, 0xF2, */ "Tensilica"},
		{/* 115, 0x73, */ "SiRF Technology"},
		{/* 116, 0xF4, */ "Bacoc Inc"},
		{/* 117, 0x75, */ "SMaL Camera Technologies"},
		{/* 118, 0x76, */ "Thomson SC"},
		{/* 119, 0xF7, */ "Airgo Networks"},
		{/* 120, 0xF8, */ "Wisair Ltd"},
		{/* 121, 0x79, */ "SigmaTel"},
		{/* 122, 0x7A, */ "Arkados"},
		{/* 123, 0xFB, */ "Compete IT gmbH Co KG"},
		{/* 124, 0x7C, */ "Eudar Technology Inc"},
		{/* 125, 0xFD, */ "Focus Enhancements"},
		{/* 126, 0xFE, */ "Xyratex"},
	},
	{ // bank #6
		{/*   1, 0x01, */ "Specular Networks"},
		{/*   2, 0x02, */ "Patriot Memory (PDP Systems)"},
		{/*   3, 0x83, */ "U-Chip Technology Corp"},
		{/*   4, 0x04, */ "Silicon Optix"},
		{/*   5, 0x85, */ "Greenfield Networks"},
		{/*   6, 0x86, */ "CompuRAM GmbH"},
		{/*   7, 0x07, */ "Stargen Inc"},
		{/*   8, 0x08, */ "NetCell Corporation"},
		{/*   9, 0x89, */ "Excalibrus Technologies Ltd"},
		{/*  10, 0x8A, */ "SCM Microsystems"},
		{/*  11, 0x0B, */ "Xsigo Systems Inc"},
		{/*  12, 0x8C, */ "CHIPS & Systems Inc"},
		{/*  13, 0x0D, */ "Tier 1 Multichip Solutions"},
		{/*  14, 0x0E, */ "CWRL Labs"},
		{/*  15, 0x8F, */ "Teradici"},
		{/*  16, 0x10, */ "Gigaram Inc"},
		{/*  17, 0x91, */ "g2 Microsystems"},
		{/*  18, 0x92, */ "PowerFlash Semiconductor"},
		{/*  19, 0x13, */ "P.A. Semi Inc"},
		{/*  20, 0x94, */ "NovaTech Solutions S.A."},
		{/*  21, 0x15, */ "c2 Microsystems Inc"},
		{/*  22, 0x16, */ "Level5 Networks"},
		{/*  23, 0x97, */ "COS Memory AG"},
		{/*  24, 0x98, */ "Innovasic Semiconductor"},
		{/*  25, 0x19, */ "02IC Co Ltd"},
		{/*  26, 0x1A, */ "Tabula Inc"},
		{/*  27, 0x9B, */ "Crucial Technology"},
		{/*  28, 0x1C, */ "Chelsio Communications"},
		{/*  29, 0x9D, */ "Solarflare Communications"},
		{/*  30, 0x9E, */ "Xambala Inc"},
		{/*  31, 0x1F, */ "EADS Astrium"},
		{/*  32, 0x20, */ "Terra Semiconductor Inc"},
		{/*  33, 0xA1, */ "Imaging Works Inc"},
		{/*  34, 0xA2, */ "Astute Networks Inc"},
		{/*  35, 0x23, */ "Tzero"},
		{/*  36, 0xA4, */ "Emulex"},
		{/*  37, 0x25, */ "Power-One"},
		{/*  38, 0x26, */ "Pulse~LINK Inc"},
		{/*  39, 0xA7, */ "Hon Hai Precision Industry"},
		{/*  40, 0xA8, */ "White Rock Networks Inc"},
		{/*  41, 0x29, */ "Telegent Systems USA Inc"},
		{/*  42, 0x2A, */ "Atrua Technologies Inc"},
		{/*  43, 0xAB, */ "Acbel Polytech Inc"},
		{/*  44, 0x2C, */ "eRide Inc"},
		{/*  45, 0xAD, */ "ULi Electronics Inc"},
		{/*  46, 0xAE, */ "Magnum Semiconductor Inc"},
		{/*  47, 0x2F, */ "neoOne Technology Inc"},
		{/*  48, 0xB0, */ "Connex Technology Inc"},
		{/*  49, 0x31, */ "Stream Processors Inc"},
		{/*  50, 0x32, */ "Focus Enhancements"},
		{/*  51, 0xB3, */ "Telecis Wireless Inc"},
		{/*  52, 0x34, */ "uNav Microelectronics"},
		{/*  53, 0xB5, */ "Tarari Inc"},
		{/*  54, 0xB6, */ "Ambric Inc"},
		{/*  55, 0x37, */ "Newport Media Inc"},
		{/*  56, 0x38, */ "VMTS"},
		{/*  57, 0xB9, */ "Enuclia Semiconductor Inc"},
		{/*  58, 0xBA, */ "Virtium Technology Inc"},
		{/*  59, 0x3B, */ "Solid State System Co Ltd"},
		{/*  60, 0xBC, */ "Kian Tech LLC"},
		{/*  61, 0x3D, */ "Artimi"},
		{/*  62, 0x3E, */ "Power Quotient International"},
		{/*  63, 0xBF, */ "Avago Technologies"},
		{/*  64, 0x40, */ "ADTechnology"},
		{/*  65, 0xC1, */ "Sigma Designs"},
		{/*  66, 0xC2, */ "SiCortex Inc"},
		{/*  67, 0x43, */ "Ventura Technology Group"},
		{/*  68, 0xC4, */ "eASIC"},
		{/*  69, 0x45, */ "M.H.S. SAS"},
		{/*  70, 0x46, */ "Micro Star International"},
		{/*  71, 0xC7, */ "Rapport Inc"},
		{/*  72, 0xC8, */ "Makway International"},
		{/*  73, 0x49, */ "Broad Reach Engineering Co"},
		{/*  74, 0x4A, */ "Semiconductor Mfg Intl Corp"},
		{/*  75, 0xCB, */ "SiConnect"},
		{/*  76, 0x4C, */ "FCI USA Inc"},
		{/*  77, 0xCD, */ "Validity Sensors"},
		{/*  78, 0xCE, */ "Coney Technology Co Ltd"},
		{/*  79, 0x4F, */ "Spans Logic"},
		{/*  80, 0xD0, */ "Neterion Inc"},
		{/*  81, 0x51, */ "Qimonda"},
		{/*  82, 0x52, */ "New Japan Radio Co Ltd"},
		{/*  83, 0xD3, */ "Velogix"},
		{/*  84, 0x54, */ "Montalvo Systems"},
		{/*  85, 0xD5, */ "iVivity Inc"},
		{/*  86, 0xD6, */ "Walton Chaintech"},
		{/*  87, 0x57, */ "AENEON"},
		{/*  88, 0x58, */ "Lorom Industrial Co Ltd"},
		{/*  89, 0xD9, */ "Radiospire Networks"},
		{/*  90, 0xDA, */ "Sensio Technologies Inc"},
		{/*  91, 0x5B, */ "Nethra Imaging"},
		{/*  92, 0xDC, */ "Hexon Technology Pte Ltd"},
		{/*  93, 0x5D, */ "CompuStocx (CSX)"},
		{/*  94, 0x5E, */ "Methode Electronics Inc"},
		{/*  95, 0xDF, */ "Connect One Ltd"},
		{/*  96, 0xE0, */ "Opulan Technologies"},
		{/*  97, 0x61, */ "Septentrio NV"},
		{/*  98, 0x62, */ "Goldenmars Technology Inc"},
		{/*  99, 0xE3, */ "Kreton Corporation"},
		{/* 100, 0x64, */ "Cochlear Ltd"},
		{/* 101, 0xE5, */ "Altair Semiconductor"},
		{/* 102, 0xE6, */ "NetEffect Inc"},
		{/* 103, 0x67, */ "Spansion Inc"},
		{/* 104, 0x68, */ "Taiwan Semiconductor Mfg"},
		{/* 105, 0xE9, */ "Emphany Systems Inc"},
		{/* 106, 0xEA, */ "ApaceWave Technologies"},
		{/* 107, 0x6B, */ "Mobilygen Corporation"},
		{/* 108, 0xEC, */ "Tego"},
		{/* 109, 0x6D, */ "Cswitch Corporation"},
		{/* 110, 0x6E, */ "Haier (Beijing) IC Design Co"},
		{/* 111, 0xEF, */ "MetaRAM"},
		{/* 112, 0x70, */ "Axel Electronics Co Ltd"},
		{/* 113, 0xF1, */ "Tilera Corporation"},
		{/* 114, 0xF2, */ "Aquantia"},
		{/* 115, 0x73, */ "Vivace Semiconductor"},
		{/* 116, 0xF4, */ "Redpine Signals"},
		{/* 117, 0x75, */ "Octalica"},
		{/* 118, 0x76, */ "InterDigital Communications"},
		{/* 119, 0xF7, */ "Avant Technology"},
		{/* 120, 0xF8, */ "Asrock Inc"},
		{/* 121, 0x79, */ "Availink"},
		{/* 122, 0x7A, */ "Quartics Inc"},
		{/* 123, 0xFB, */ "Element CXI"},
		{/* 124, 0x7C, */ "Innovaciones Microelectronicas"},
		{/* 125, 0xFD, */ "VeriSilicon Microelectronics"},
		{/* 126, 0xFE, */ "W5 Networks"},
	},
	{ // bank #7
		{/*   1, 0x01, */ "MOVEKING"},
		{/*   2, 0x02, */ "Mavrix Technology Inc"},
		{/*   3, 0x83, */ "CellGuide Ltd"},
		{/*   4, 0x04, */ "Faraday Technology"},
		{/*   5, 0x85, */ "Diablo Technologies Inc"},
		{/*   6, 0x86, */ "Jennic"},
		{/*   7, 0x07, */ "Octasic"},
		{/*   8, 0x08, */ "Molex Incorporated"},
		{/*   9, 0x89, */ "3Leaf Networks"},
		{/*  10, 0x8A, */ "Bright Micron Technology"},
		{/*  11, 0x0B, */ "Netxen"},
		{/*  12, 0x8C, */ "NextWave Broadband Inc"},
		{/*  13, 0x0D, */ "DisplayLink"},
		{/*  14, 0x0E, */ "ZMOS Technology"},
		{/*  15, 0x8F, */ "Tec-Hill"},
		{/*  16, 0x10, */ "Multigig Inc"},
		{/*  17, 0x91, */ "Amimon"},
		{/*  18, 0x92, */ "Euphonic Technologies Inc"},
		{/*  19, 0x13, */ "BRN Phoenix"},
		{/*  20, 0x94, */ "InSilica"},
		{/*  21, 0x15, */ "Ember Corporation"},
		{/*  22, 0x16, */ "Avexir Technologies Corporation"},
		{/*  23, 0x97, */ "Echelon Corporation"},
		{/*  24, 0x98, */ "Edgewater Computer Systems"},
		{/*  25, 0x19, */ "XMOS Semiconductor Ltd"},
		{/*  26, 0x1A, */ "GENUSION Inc"},
		{/*  27, 0x9B, */ "Memory Corp NV"},
		{/*  28, 0x1C, */ "SiliconBlue Technologies"},
		{/*  29, 0x9D, */ "Rambus Inc"},
		{/*  30, 0x9E, */ "Andes Technology Corporation"},
		{/*  31, 0x1F, */ "Coronis Systems"},
		{/*  32, 0x20, */ "Achronix Semiconductor"},
		{/*  33, 0xA1, */ "Siano Mobile Silicon Ltd"},
		{/*  34, 0xA2, */ "Semtech Corporation"},
		{/*  35, 0x23, */ "Pixelworks Inc"},
		{/*  36, 0xA4, */ "Gaisler Research AB"},
		{/*  37, 0x25, */ "Teranetics"},
		{/*  38, 0x26, */ "Toppan Printing Co Ltd"},
		{/*  39, 0xA7, */ "Kingxcon"},
		{/*  40, 0xA8, */ "Silicon Integrated Systems"},
		{/*  41, 0x29, */ "I-O Data Device Inc"},
		{/*  42, 0x2A, */ "NDS Americas Inc"},
		{/*  43, 0xAB, */ "Solomon Systech Limited"},
		{/*  44, 0x2C, */ "On Demand Microelectronics"},
		{/*  45, 0xAD, */ "Amicus Wireless Inc"},
		{/*  46, 0xAE, */ "SMARDTV SNC"},
		{/*  47, 0x2F, */ "Comsys Communication Ltd"},
		{/*  48, 0xB0, */ "Movidia Ltd"},
		{/*  49, 0x31, */ "Javad GNSS Inc"},
		{/*  50, 0x32, */ "Montage Technology Group"},
		{/*  51, 0xB3, */ "Trident Microsystems"},
		{/*  52, 0x34, */ "Super Talent"},
		{/*  53, 0xB5, */ "Optichron Inc"},
		{/*  54, 0xB6, */ "Future Waves UK Ltd"},
		{/*  55, 0x37, */ "SiBEAM Inc"},
		{/*  56, 0x38, */ "InicoreInc"},
		{/*  57, 0xB9, */ "Virident Systems"},
		{/*  58, 0xBA, */ "M2000 Inc"},
		{/*  59, 0x3B, */ "ZeroG Wireless Inc"},
		{/*  60, 0xBC, */ "Gingle Technology Co Ltd"},
		{/*  61, 0x3D, */ "Space Micro Inc"},
		{/*  62, 0x3E, */ "Wilocity"},
		{/*  63, 0xBF, */ "Novafora Inc"},
		{/*  64, 0x40, */ "iKoa Corporation"},
		{/*  65, 0xC1, */ "ASint Technology"},
		{/*  66, 0xC2, */ "Ramtron"},
		{/*  67, 0x43, */ "Plato Networks Inc"},
		{/*  68, 0xC4, */ "IPtronics AS"},
		{/*  69, 0x45, */ "Infinite-Memories"},
		{/*  70, 0x46, */ "Parade Technologies Inc"},
		{/*  71, 0xC7, */ "Dune Networks"},
		{/*  72, 0xC8, */ "GigaDevice Semiconductor"},
		{/*  73, 0x49, */ "Modu Ltd"},
		{/*  74, 0x4A, */ "CEITEC"},
		{/*  75, 0xCB, */ "Northrop Grumman"},
		{/*  76, 0x4C, */ "XRONET Corporation"},
		{/*  77, 0xCD, */ "Sicon Semiconductor AB"},
		{/*  78, 0xCE, */ "Atla Electronics Co Ltd"},
		{/*  79, 0x4F, */ "TOPRAM Technology"},
		{/*  80, 0xD0, */ "Silego Technology Inc"},
		{/*  81, 0x51, */ "Kinglife"},
		{/*  82, 0x52, */ "Ability Industries Ltd"},
		{/*  83, 0xD3, */ "Silicon Power Computer & Communications"},
		{/*  84, 0x54, */ "Augusta Technology Inc"},
		{/*  85, 0xD5, */ "Nantronics Semiconductors"},
		{/*  86, 0xD6, */ "Hilscher Gesellschaft"},
		{/*  87, 0x57, */ "Quixant Ltd"},
		{/*  88, 0x58, */ "Percello Ltd"},
		{/*  89, 0xD9, */ "NextIO Inc"},
		{/*  90, 0xDA, */ "Scanimetrics Inc"},
		{/*  91, 0x5B, */ "FS-Semi Company Ltd"},
		{/*  92, 0xDC, */ "Infinera Corporation"},
		{/*  93, 0x5D, */ "SandForce Inc"},
		{/*  94, 0x5E, */ "Lexar Media"},
		{/*  95, 0xDF, */ "Teradyne Inc"},
		{/*  96, 0xE0, */ "Memory Exchange Corp"},
		{/*  97, 0x61, */ "Suzhou Smartek Electronics"},
		{/*  98, 0x62, */ "Avantium Corporation"},
		{/*  99, 0xE3, */ "ATP Electronics Inc"},
		{/* 100, 0x64, */ "Valens Semiconductor Ltd"},
		{/* 101, 0xE5, */ "Agate Logic Inc"},
		{/* 102, 0xE6, */ "Netronome"},
		{/* 103, 0x67, */ "Zenverge Inc"},
		{/* 104, 0x68, */ "N-trig Ltd"},
		{/* 105, 0xE9, */ "SanMax Technologies Inc"},
		{/* 106, 0xEA, */ "Contour Semiconductor Inc"},
		{/* 107, 0x6B, */ "TwinMOS"},
		{/* 108, 0xEC, */ "Silicon Systems Inc"},
		{/* 109, 0x6D, */ "V-Color Technology Inc"},
		{/* 110, 0x6E, */ "Certicom Corporation"},
		{/* 111, 0xEF, */ "JSC ICC Milandr"},
		{/* 112, 0x70, */ "PhotoFast Global Inc"},
		{/* 113, 0xF1, */ "InnoDisk Corporation"},
		{/* 114, 0xF2, */ "Muscle Power"},
		{/* 115, 0x73, */ "Energy Micro"},
		{/* 116, 0xF4, */ "Innofidei"},
		{/* 117, 0x75, */ "CopperGate Communications"},
		{/* 118, 0x76, */ "Holtek Semiconductor Inc"},
		{/* 119, 0xF7, */ "Myson Century Inc"},
		{/* 120, 0xF8, */ "FIDELIX"},
		{/* 121, 0x79, */ "Red Digital Cinema"},
		{/* 122, 0x7A, */ "Densbits Technology"},
		{/* 123, 0xFB, */ "Zempro"},
		{/* 124, 0x7C, */ "MoSys"},
		{/* 125, 0xFD, */ "Provigent"},
		{/* 126, 0xFE, */ "Triad Semiconductor Inc"},
	},
	{ // bank #8
		{/*   1, 0x01, */ "Siklu Communication Ltd"},
		{/*   2, 0x02, */ "A Force Manufacturing Ltd"},
		{/*   3, 0x83, */ "Strontium"},
		{/*   4, 0x04, */ "ALi Corp (Abilis Systems)"},
		{/*   5, 0x85, */ "Siglead Inc"},
		{/*   6, 0x86, */ "Ubicom Inc"},
		{/*   7, 0x07, */ "Unifosa Corporation"},
		{/*   8, 0x08, */ "Stretch Inc"},
		{/*   9, 0x89, */ "Lantiq Deutschland GmbH"},
		{/*  10, 0x8A, */ "Visipro."},
		{/*  11, 0x0B, */ "EKMemory"},
		{/*  12, 0x8C, */ "Microelectronics Institute ZTE"},
		{/*  13, 0x0D, */ "u-blox AG"},
		{/*  14, 0x0E, */ "Carry Technology Co Ltd"},
		{/*  15, 0x8F, */ "Nokia"},
		{/*  16, 0x10, */ "King Tiger Technology"},
		{/*  17, 0x91, */ "Sierra Wireless"},
		{/*  18, 0x92, */ "HT Micron"},
		{/*  19, 0x13, */ "Albatron Technology Co Ltd"},
		{/*  20, 0x94, */ "Leica Geosystems AG"},
		{/*  21, 0x15, */ "BroadLight"},
		{/*  22, 0x16, */ "AEXEA"},
		{/*  23, 0x97, */ "ClariPhy Communications Inc"},
		{/*  24, 0x98, */ "Green Plug"},
		{/*  25, 0x19, */ "Design Art Networks"},
		{/*  26, 0x1A, */ "Mach Xtreme Technology Ltd"},
		{/*  27, 0x9B, */ "ATO Solutions Co Ltd"},
		{/*  28, 0x1C, */ "Ramsta"},
		{/*  29, 0x9D, */ "Greenliant Systems Ltd"},
		{/*  30, 0x9E, */ "Teikon"},
		{/*  31, 0x1F, */ "Antec Hadron"},
		{/*  32, 0x20, */ "NavCom Technology Inc"},
		{/*  33, 0xA1, */ "Shanghai Fudan Microelectronics"},
		{/*  34, 0xA2, */ "Calxeda Inc"},
		{/*  35, 0x23, */ "JSC EDC Electronics"},
		{/*  36, 0xA4, */ "Kandit Technology Co Ltd"},
		{/*  37, 0x25, */ "Ramos Technology"},
		{/*  38, 0x26, */ "Goldenmars Technology"},
		{/*  39, 0xA7, */ "XeL Technology Inc"},
		{/*  40, 0xA8, */ "Newzone Corporation"},
		{/*  41, 0x29, */ "ShenZhen MercyPower Tech"},
		{/*  42, 0x2A, */ "Nanjing Yihuo Technology"},
		{/*  43, 0xAB, */ "Nethra Imaging Inc"},
		{/*  44, 0x2C, */ "SiTel Semiconductor BV"},
		{/*  45, 0xAD, */ "SolidGear Corporation"},
		{/*  46, 0xAE, */ "Topower Computer Ind Co Ltd"},
		{/*  47, 0x2F, */ "Wilocity"},
		{/*  48, 0xB0, */ "Profichip GmbH"},
		{/*  49, 0x31, */ "Gerad Technologies"},
		{/*  50, 0x32, */ "Ritek Corporation"},
		{/*  51, 0xB3, */ "Gomos Technology Limited"},
		{/*  52, 0x34, */ "Memoright Corporation"},
		{/*  53, 0xB5, */ "D-Broad Inc"},
		{/*  54, 0xB6, */ "HiSilicon Technologies"},
		{/*  55, 0x37, */ "Syndiant Inc."},
		{/*  56, 0x38, */ "Enverv Inc"},
		{/*  57, 0xB9, */ "Cognex"},
		{/*  58, 0xBA, */ "Xinnova Technology Inc"},
		{/*  59, 0x3B, */ "Ultron AG"},
		{/*  60, 0xBC, */ "Concord Idea Corporation"},
		{/*  61, 0x3D, */ "AIM Corporation"},
		{/*  62, 0x3E, */ "Lifetime Memory Products"},
		{/*  63, 0xBF, */ "Ramsway"},
		{/*  64, 0x40, */ "Recore Systems B.V."},
		{/*  65, 0xC1, */ "Haotian Jinshibo Science Tech"},
		{/*  66, 0xC2, */ "Being Advanced Memory"},
		{/*  67, 0x43, */ "Adesto Technologies"},
		{/*  68, 0xC4, */ "Giantec Semiconductor Inc"},
		{/*  69, 0x45, */ "HMD Electronics AG"},
		{/*  70, 0x46, */ "Gloway International (HK)"},
		{/*  71, 0xC7, */ "Kingcore"},
		{/*  72, 0xC8, */ "Anucell Technology Holding"},
		{/*  73, 0x49, */ "Accord Software & Systems Pvt. Ltd"},
		{/*  74, 0x4A, */ "Active-Semi Inc"},
		{/*  75, 0xCB, */ "Denso Corporation"},
		{/*  76, 0x4C, */ "TLSI Inc"},
		{/*  77, 0xCD, */ "Qidan"},
		{/*  78, 0xCE, */ "Mustang"},
		{/*  79, 0x4F, */ "Orca Systems"},
		{/*  80, 0xD0, */ "Passif Semiconductor"},
		{/*  81, 0x51, */ "GigaDevice Semiconductor (Beijing)"},
		{/*  82, 0x52, */ "Memphis Electronic"},
		{/*  83, 0xD3, */ "Beckhoff Automation GmbH"},
		{/*  84, 0x54, */ "Harmony Semiconductor Corp"},
		{/*  85, 0xD5, */ "Air Computers SRL"},
		{/*  86, 0xD6, */ "TMT Memory"},
		{/*  87, 0x57, */ "Eorex Corporation"},
		{/*  88, 0x58, */ "Xingtera"},
		{/*  89, 0xD9, */ "Netsol"},
		{/*  90, 0xDA, */ "Bestdon Technology Co Ltd"},
		{/*  91, 0x5B, */ "Baysand Inc"},
		{/*  92, 0xDC, */ "Uroad Technology Co Ltd"},
		{/*  93, 0x5D, */ "Wilk Elektronik S.A."},
		{/*  94, 0x5E, */ "AAI"},
		{/*  95, 0xDF, */ "Harman"},
		{/*  96, 0xE0, */ "Berg Microelectronics Inc"},
		{/*  97, 0x61, */ "ASSIA Inc"},
		{/*  98, 0x62, */ "Visiontek Products LLC"},
		{/*  99, 0xE3, */ "OCMEMORY"},
		{/* 100, 0x64, */ "Welink Solution Inc"},
		{/* 101, 0xE5, */ "Shark Gaming"},
		{/* 102, 0xE6, */ "Avalanche Technology"},
		{/* 103, 0x67, */ "R&D Center ELVEES OJSC"},
		{/* 104, 0x68, */ "KingboMars Technology Co Ltd"},
		{/* 105, 0xE9, */ "High Bridge Solutions Industria Eletronica"},
		{/* 106, 0xEA, */ "Transcend Technology Co Ltd"},
		{/* 107, 0x6B, */ "Everspin Technologies"},
		{/* 108, 0xEC, */ "Hon-Hai Precision"},
		{/* 109, 0x6D, */ "Smart Storage Systems"},
		{/* 110, 0x6E, */ "Toumaz Group"},
		{/* 111, 0xEF, */ "Zentel Electronics Corporation"},
		{/* 112, 0x70, */ "Panram International Corporation"},
		{/* 113, 0xF1, */ "Silicon Space Technology"},
		{/* 114, 0xF2, */ "LITE-ON IT Corporation"},
		{/* 115, 0x73, */ "Inuitive"},
		{/* 116, 0xF4, */ "HMicro"},
		{/* 117, 0x75, */ "BittWare Inc"},
		{/* 118, 0x76, */ "GLOBALFOUNDRIES"},
		{/* 119, 0xF7, */ "ACPI Digital Co Ltd"},
		{/* 120, 0xF8, */ "Annapurna Labs"},
		{/* 121, 0x79, */ "AcSiP Technology Corporation"},
		{/* 122, 0x7A, */ "Idea! Electronic Systems"},
		{/* 123, 0xFB, */ "Gowe Technology Co Ltd"},
		{/* 124, 0x7C, */ "Hermes Testing Solutions Inc"},
		{/* 125, 0xFD, */ "Positivo BGH"},
		{/* 126, 0xFE, */ "Intelligence Silicon Technology"},
	},
	{ // bank #9
		{/*  1, 0x01, */ "3D PLUS"},
		{/*  2, 0x02, */ "Diehl Aerospace" },
		{/*  3, 0x83, */ "Fairchild" },
		{/*  4, 0x04, */ "Mercury Systems" },
		{/*  5, 0x85, */ "Sonics Inc" },
		{/*  6, 0x86, */ "Emerson Automation Solutions" },
		{/*  7, 0x07, */ "Shenzhen Jinge Information Co Ltd" },
		{/*  8, 0x08, */ "SCWW" },
		{/*  9, 0x89, */ "Silicon Motion Inc" },
		{/*  10, 0x8A, */ "Anurag" },
		{/*  11, 0x0B, */ "King Kong" },
		{/*  12, 0x8C, */ "FROM30 Co Ltd" },
		{/*  13, 0x0D, */ "Gowin Semiconductor Corp" },
		{/*  14, 0x0E, */ "Fremont Micro Devices Ltd" },
		{/*  15, 0x8F, */ "Ericsson Modems" },
		{/*  16, 0x10, */ "Exelis" },
		{/*  17, 0x91, */ "Satixfy Ltd" },
		{/*  18, 0x92, */ "Galaxy Microsystems Ltd" },
		{/*  19, 0x13, */ "Gloway International Co Ltd" },
		{/*  20, 0x94, */ "Lab" },
		{/*  21, 0x15, */ "Smart Energy Instruments" },
		{/*  22, 0x16, */ "Approved Memory Corporation" },
		{/*  23, 0x97, */ "Axell Corporation" },
		{/*  24, 0x98, */ "Essencore Limited" },
		{/*  25, 0x19, */ "Phytium" },
		{/*  26, 0x1A, */ "UniIC Semiconductors Co Ltd" },
		{/*  27, 0x9B, */ "Ambiq Micro" },
		{/*  28, 0x1C, */ "eveRAM Technology Inc" },
		{/*  29, 0x9D, */ "Infomax" },
		{/*  30, 0x9E, */ "Butterfly Network Inc" },
		{/*  31, 0x1F, */ "Shenzhen City Gcai Electronics" },
		{/*  32, 0x20, */ "Stack Devices Corporation" },
		{/*  33, 0xA1, */ "ADK Media Group" },
		{/*  34, 0xA2, */ "TSP Global Co Ltd" },
		{/*  35, 0x23, */ "HighX" },
		{/*  36, 0xA4, */ "Shenzhen Elicks Technology" },
		{/*  37, 0x25, */ "XinKai/Silicon Kaiser" },
		{/*  38, 0x26, */ "Google Inc" },
		{/*  39, 0xA7, */ "Dasima International Development" },
		{/*  40, 0xA8, */ "Leahkinn Technology Limited" },
		{/*  41, 0x29, */ "HIMA Paul Hildebrandt GmbH Co KG" },
		{/*  42, 0x2A, */ "Keysight Technologies" },
		{/*  43, 0xAB, */ "Techcomp International (Fastable)" },
		{/*  44, 0x2C, */ "Ancore Technology Corporation" },
		{/*  45, 0xAD, */ "Nuvoton" },
		{/*  46, 0xAE, */ "Korea Uhbele International Group Ltd" },
		{/*  47, 0x2F, */ "Ikegami Tsushinki Co Ltd" },
		{/*  48, 0xB0, */ "RelChip Inc" },
		{/*  49, 0x31, */ "Baikal Electronics" },
		{/*  50, 0x32, */ "Nemostech Inc" },
		{/*  51, 0xB3, */ "Memorysolution GmbH" },
		{/*  52, 0x34, */ "Silicon Integrated Systems Corporation" },
		{/*  53, 0xB5, */ "Xiede" },
		{/*  54, 0xB6, */ "BRC" },
		{/*  55, 0x37, */ "Flash Chi" },
		{/*  56, 0x38, */ "Jone" },
		{/*  57, 0xB9, */ "GCT Semiconductor Inc" },
		{/*  58, 0xBA, */ "Hong Kong Zetta Device Technology" },
		{/*  59, 0x3B, */ "Unimemory Technology(s) Pte Ltd" },
		{/*  60, 0xBC, */ "Cuso" },
		{/*  61, 0x3D, */ "Kuso" },
		{/*  62, 0x3E, */ "Uniquify Inc" },
		{/*  63, 0xBF, */ "Skymedi Corporation" },
		{/*  64, 0x40, */ "Core Chance Co Ltd" },
		{/*  65, 0xC1, */ "Tekism Co Ltd" },
		{/*  66, 0xC2, */ "Seagate Technology PLC" },
		{/*  67, 0x43, */ "Hong Kong Gaia Group Co Limited" },
		{/*  68, 0xC4, */ "Gigacom Semiconductor LLC" },
		{/*  69, 0x45, */ "V2 Technologies" },
		{/*  70, 0x46, */ "TLi" },
		{/*  71, 0xC7, */ "Neotion" },
		{/*  72, 0xC8, */ "Lenovo" },
		{/*  73, 0x49, */ "Shenzhen Zhongteng Electronic Corp Ltd" },
		{/*  74, 0x4A, */ "Compound Photonics" },
		{/*  75, 0xCB, */ "in2H2 inc" },
		{/*  76, 0x4C, */ "Shenzhen Pango Microsystems Co Ltd" },
		{/*  77, 0xCD, */ "Vasekey" },
		{/*  78, 0xCE, */ "Cal-Comp Industria de Semicondutores" },
		{/*  79, 0x4F, */ "Eyenix Co Ltd" },
		{/*  80, 0xD0, */ "Heoriady" },
		{/*  81, 0x51, */ "Accelerated Memory Production Inc" },
		{/*  82, 0x52, */ "INVECAS Inc" },
		{/*  83, 0xD3, */ "AP Memory" },
		{/*  84, 0x54, */ "Douqi Technology" },
		{/*  85, 0xD5, */ "Etron Technology Inc" },
		{/*  86, 0xD6, */ "Indie Semiconductor" },
		{/*  87, 0x57, */ "Socionext Inc" },
		{/*  88, 0x58, */ "HGST" },
		{/*  89, 0xD9, */ "EVGA" },
		{/*  90, 0xDA, */ "Audience Inc" },
		{/*  91, 0x5B, */ "EpicGear" },
		{/*  92, 0xDC, */ "Vitesse Enterprise Co" },
		{/*  93, 0x5D, */ "Foxtronn International Corporation" },
		{/*  94, 0x5E, */ "Bretelon Inc" },
		{/*  95, 0xDF, */ "Graphcore" },
		{/*  96, 0xE0, */ "Eoplex Inc" },
		{/*  97, 0x61, */ "MaxLinear Inc" },
		{/*  98, 0x62, */ "ETA Devices" },
		{/*  99, 0xE3, */ "LOKI" },
		{/* 100, 0x64, */ "IMS Electronics Co Ltd" },
		{/* 101, 0xE5, */ "Dosilicon Co Ltd" },
		{/* 102, 0xE6, */ "Dolphin Integration" },
		{/* 103, 0x67, */ "Shenzhen Mic Electronics Technolog" },
		{/* 104, 0x68, */ "Boya Microelectronics Inc" },
		{/* 105, 0xE9, */ "Geniachip (Roche)" },
		{/* 106, 0xEA, */ "Axign" },
		{/* 107, 0x6B, */ "Kingred Electronic Technology Ltd" },
		{/* 108, 0xEC, */ "Chao Yue Zhuo Computer Business Dept." },
		{/* 109, 0x6D, */ "Guangzhou Si Nuo Electronic Technology." },
		{/* 110, 0x6E, */ "Crocus Technology Inc" },
		{/* 111, 0xEF, */ "Creative Chips GmbH" },
		{/* 112, 0x70, */ "GE Aviation Systems LLC." },
		{/* 113, 0xF1, */ "Asgard" },
		{/* 114, 0xF2, */ "Good Wealth Technology Ltd" },
		{/* 115, 0x73, */ "TriCor Technologies" },
		{/* 116, 0xF4, */ "Nova-Systems GmbH" },
		{/* 117, 0x75, */ "JUHOR" },
		{/* 118, 0x76, */ "Zhuhai Douke Commerce Co Ltd" },
		{/* 119, 0xF7, */ "DSL Memory" },
		{/* 120, 0xF8, */ "Anvo-Systems Dresden GmbH" },
		{/* 121, 0x79, */ "Realtek" },
		{/* 122, 0x7A, */ "AltoBeam" },
		{/* 123, 0xFB, */ "Wave Computing" },
		{/* 124, 0x7C, */ "Beijing TrustNet Technology Co Ltd" },
		{/* 125, 0xFD, */ "Innovium Inc" },
		{/* 126, 0xFE, */ "Starsway Technology Limited" },
	},
	{ // bank #10
		{/*   1, 0x01, */ "Weltronics Co LTD"},
		{/*   2, 0x02, */ "VMware Inc" },
		{/*   3, 0x83, */ "Hewlett Packard Enterprise" },
		{/*   4, 0x04, */ "INTENSO" },
		{/*   5, 0x85, */ "Puya Semiconductor" },
		{/*   6, 0x86, */ "MEMORFI" },
		{/*   7, 0x07, */ "MSC Technologies GmbH" },
		{/*   8, 0x08, */ "Txrui" },
		{/*   9, 0x89, */ "SiFive Inc" },
		{/*  10, 0x8A, */ "Spreadtrum Communications" },
		{/*  11, 0x0B, */ "XTX Technology Limited" },
		{/*  12, 0x8C, */ "UMAX Technology" },
		{/*  13, 0x0D, */ "Shenzhen Yong Sheng Technology" },
		{/*  14, 0x0E, */ "SNOAMOO (Shenzhen Kai Zhuo Yue)" },
		{/*  15, 0x8F, */ "Daten Tecnologia LTDA" },
		{/*  16, 0x10, */ "Shenzhen XinRuiYan Electronics" },
		{/*  17, 0x91, */ "Eta Compute" },
		{/*  18, 0x92, */ "Energous" },
		{/*  19, 0x13, */ "Raspberry Pi Trading Ltd" },
		{/*  20, 0x94, */ "Shenzhen Chixingzhe Tech Co Ltd" },
		{/*  21, 0x15, */ "Silicon Mobility" },
		{/*  22, 0x16, */ "IQ-Analog Corporation" },
		{/*  23, 0x97, */ "Uhnder Inc" },
		{/*  24, 0x98, */ "Impinj" },
		{/*  25, 0x19, */ "DEPO Computers" },
		{/*  26, 0x1A, */ "Nespeed Sysems" },
		{/*  27, 0x9B, */ "Yangtze Memory Technologies Co Ltd" },
		{/*  28, 0x1C, */ "MemxPro Inc" },
		{/*  29, 0x9D, */ "Tammuz Co Ltd" },
		{/*  30, 0x9E, */ "Allwinner Technology" },
		{/*  31, 0x1F, */ "Shenzhen City Futian District Qing Xuan Tong Computer Trading Firm" },
		{/*  32, 0x20, */ "XMC" },
		{/*  33, 0xA1, */ "Teclast" },
		{/*  34, 0xA2, */ "Maxsun" },
		{/*  35, 0x23, */ "Haiguang Integrated Circuit Design" },
		{/*  36, 0xA4, */ "RamCENTER Technology" },
		{/*  37, 0x25, */ "Phison Electronics Corporation" },
		{/*  38, 0x26, */ "Guizhou Huaxintong Semi-Conductor" },
		{/*  39, 0xA7, */ "Network Intelligence" },
		{/*  40, 0xA8, */ "Continental Technology (Holdings)" },
		{/*  41, 0x29, */ "Guangzhou Huayan Suning Electronic" },
		{/*  42, 0x2A, */ "Guangzhou Zhouji Electronic Co Ltd" },
		{/*  43, 0xAB, */ "Shenzhen Giant Hui Kang Tech Co Ltd" },
		{/*  44, 0x2C, */ "Shenzhen Yilong Innovative Co Ltd" },
		{/*  45, 0xAD, */ "Neo Forza" },
		{/*  46, 0xAE, */ "Lyontek Inc" },
		{/*  47, 0x2F, */ "Shanghai Kuxin Microelectronics Ltd" },
		{/*  48, 0xB0, */ "Shenzhen Larix Technology Co Ltd" },
		{/*  49, 0x31, */ "Qbit Semiconductor Ltd" },
		{/*  50, 0x32, */ "Insignis Technology Corporation" },
		{/*  51, 0xB3, */ "Lanson Memory Co Ltd" },
		{/*  52, 0x34, */ "Shenzhen Superway Electronics Co Ltd" },
		{/*  53, 0xB5, */ "Canaan-Creative Co Ltd" },
		{/*  54, 0xB6, */ "Black Diamond Memory" },
		{/*  55, 0x37, */ "Shenzhen City Parker Baking Electronics" },
		{/*  56, 0x38, */ "Shenzhen Baihong Technology Co Ltd" },
		{/*  57, 0xB9, */ "GEO Semiconductors" },
		{/*  58, 0xBA, */ "OCPC" },
		{/*  59, 0x3B, */ "Artery Technology Co Ltd" },
		{/*  60, 0xBC, */ "Jinyu" },
		{/*  61, 0x3D, */ "ShenzhenYing Chi Technology Development" },
		{/*  62, 0x3E, */ "Shenzhen Pengcheng Xin Technology" },
		{/*  63, 0xBF, */ "Pegasus Semiconductor (Shanghai) Co" },
		{/*  64, 0x40, */ "Mythic Inc" },
		{/*  65, 0xC1, */ "Elmos Semiconductor AG" },
		{/*  66, 0xC2, */ "Kllisre" },
		{/*  67, 0x43, */ "Shenzhen Winconway Technology" },
		{/*  68, 0xC4, */ "Shenzhen Xingmem Technology Corp" },
		{/*  69, 0x45, */ "Gold Key Technology Co Ltd" },
		{/*  70, 0x46, */ "Habana Labs Ltd" },
		{/*  71, 0xC7, */ "Hoodisk Electronics Co Ltd" },
		{/*  72, 0xC8, */ "SemsoTai (SZ) Technology Co Ltd" },
		{/*  73, 0x49, */ "OM Nanotech Pvt. Ltd" },
		{/*  74, 0x4A, */ "Shenzhen Zhifeng Weiye Technology" },
		{/*  75, 0xCB, */ "Xinshirui (Shenzhen) Electronics Co" },
		{/*  76, 0x4C, */ "Guangzhou Zhong Hao Tian Electronic" },
		{/*  77, 0xCD, */ "Shenzhen Longsys Electronics Co Ltd" },
		{/*  78, 0xCE, */ "Deciso B.V." },
		{/*  79, 0x4F, */ "Puya Semiconductor (Shenzhen)" },
		{/*  80, 0xD0, */ "Shenzhen Veineda Technology Co Ltd" },
		{/*  81, 0x51, */ "Antec Memory" },
		{/*  82, 0x52, */ "Cortus SAS" },
		{/*  83, 0xD3, */ "Dust Leopard" },
		{/*  84, 0x54, */ "MyWo AS" },
		{/*  85, 0xD5, */ "J&A Information Inc" },
		{/*  86, 0xD6, */ "Shenzhen JIEPEI Technology Co Ltd" },
		{/*  87, 0x57, */ "Heidelberg University" },
		{/*  88, 0x58, */ "Flexxon PTE Ltd" },
		{/*  89, 0xD9, */ "Wiliot" },
		{/*  90, 0xDA, */ "Raysun Electronics International Ltd" },
		{/*  91, 0x5B, */ "Aquarius Production Company LLC" },
		{/*  92, 0xDC, */ "MACNICA DHW LTDA" },
		{/*  93, 0x5D, */ "Intelimem" },
		{/*  94, 0x5E, */ "Zbit Semiconductor Inc" },
		{/*  95, 0xDF, */ "Shenzhen Technology Co Ltd" },
		{/*  96, 0xE0, */ "Signalchip" },
		{/*  97, 0x61, */ "Shenzen Recadata Storage Technology" },
		{/*  98, 0x62, */ "Hyundai Technology" },
		{/*  99, 0xE3, */ "Shanghai Fudi Investment Development" },
		{/* 100, 0x64, */ "Aixi Technology" },
		{/* 101, 0xE5, */ "Tecon MT" },
		{/* 102, 0xE6, */ "Onda Electric Co Ltd" },
		{/* 103, 0x67, */ "Jinshen" },
		{/* 104, 0x68, */ "Kimtigo Semiconductor (HK) Limited" },
		{/* 105, 0xE9, */ "IIT Madras" },
		{/* 106, 0xEA, */ "Shenshan (Shenzhen) Electronic" },
		{/* 107, 0x6B, */ "Hefei Core Storage Electronic Limited" },
		{/* 108, 0xEC, */ "Colorful Technology Ltd" },
		{/* 109, 0x6D, */ "Visenta (Xiamen) Technology Co Ltd" },
		{/* 110, 0x6E, */ "Roa Logic BV" },
		{/* 111, 0xEF, */ "NSITEXE Inc" },
		{/* 112, 0x70, */ "Hong Kong Hyunion Electronics" },
		{/* 113, 0xF1, */ "ASK Technology Group Limited" },
		{/* 114, 0xF2, */ "GIGA-BYTE Technology Co Ltd" },
		{/* 115, 0x73, */ "Terabyte Co Ltd" },
		{/* 116, 0xF4, */ "Hyundai Inc" },
		{/* 117, 0x75, */ "EXCELERAM" },
		{/* 118, 0x76, */ "PsiKick" },
		{/* 119, 0xF7, */ "Netac Technology Co Ltd" },
		{/* 120, 0xF8, */ "PCCOOLER" },
		{/* 121, 0x79, */ "Jiangsu Huacun Electronic Technology" },
		{/* 122, 0x7A, */ "Shenzhen Micro Innovation Industry" },
		{/* 123, 0xFB, */ "Beijing Tongfang Microelectronics Co" },
		{/* 124, 0x7C, */ "XZN Storage Technology" },
		{/* 125, 0xFD, */ "ChipCraft Sp. z.o.o." },
		{/* 126, 0xFE, */ "ALLFLASH Technology Limited" },
	},
	{ // bank #11
		{/*   1, 0x01, */ "Foerd Technology Co Ltd"},
		{/*   2, 0x02, */ "KingSpec" },
		{/*   3, 0x83, */ "Codasip GmbH" },
		{/*   4, 0x04, */ "SL Link Co Ltd" },
		{/*   5, 0x85, */ "Shenzhen Kefu Technology Co Limited" },
		{/*   6, 0x86, */ "Shenzhen ZST Electronics Technology" },
		{/*   7, 0x07, */ "Kyokuto Electronic Inc" },
		{/*   8, 0x08, */ "Warrior Technology" },
		{/*   9, 0x89, */ "TRINAMIC Motion Control GmbH & Co" },
		{/*  10, 0x8A, */ "PixelDisplay Inc" },
		{/*  11, 0x0B, */ "Shenzhen Futian District Bo Yueda Elec" },
		{/*  12, 0x8C, */ "Richtek Power" },
		{/*  13, 0x0D, */ "Shenzhen LianTeng Electronics Co Ltd" },
		{/*  14, 0x0E, */ "AITC Memory" },
		{/*  15, 0x8F, */ "UNIC Memory Technology Co Ltd" },
		{/*  16, 0x10, */ "Shenzhen Huafeng Science Technology" },
		{/*  17, 0x91, */ "CXMT" },
		{/*  18, 0x92, */ "Guangzhou Xinyi Heng Computer Trading Firm" },
		{/*  19, 0x13, */ "SambaNova Systems" },
		{/*  20, 0x94, */ "V-GEN" },
		{/*  21, 0x15, */ "Jump Trading" },
		{/*  22, 0x16, */ "Ampere Computing" },
		{/*  23, 0x97, */ "Shenzhen Zhongshi Technology Co Ltd" },
		{/*  24, 0x98, */ "Shenzhen Zhongtian Bozhong Technology" },
		{/*  25, 0x19, */ "Tri-Tech International" },
		{/*  26, 0x1A, */ "Silicon Intergrated Systems Corporation" },
		{/*  27, 0x9B, */ "Shenzhen HongDingChen Information" },
		{/*  28, 0x1C, */ "Plexton Holdings Limited" },
		{/*  29, 0x9D, */ "AMS (Jiangsu Advanced Memory Semi)" },
		{/*  30, 0x9E, */ "Wuhan Jing Tian Interconnected Tech Co" },
		{/*  31, 0x1F, */ "Axia Memory Technology" },
		{/*  32, 0x20, */ "Chipset Technology Holding Limited" },
		{/*  33, 0xA1, */ "Shenzhen Xinshida Technology Co Ltd" },
		{/*  34, 0xA2, */ "Shenzhen Chuangshifeida Technology" },
		{/*  35, 0x23, */ "Guangzhou MiaoYuanJi Technology" },
		{/*  36, 0xA4, */ "ADVAN Inc" },
		{/*  37, 0x25, */ "Shenzhen Qianhai Weishengda Electronic Commerce Company Ltd" },
		{/*  38, 0x26, */ "Guangzhou Guang Xie Cheng Trading" },
		{/*  39, 0xA7, */ "StarRam International Co Ltd" },
		{/*  40, 0xA8, */ "Shen Zhen XinShenHua Tech Co Ltd" },
		{/*  41, 0x29, */ "UltraMemory Inc" },
		{/*  42, 0x2A, */ "New Coastline Global Tech Industry Co" },
		{/*  43, 0xAB, */ "Sinker" },
		{/*  44, 0x2C, */ "Diamond" },
		{/*  45, 0xAD, */ "PUSKILL" },
		{/*  46, 0xAE, */ "Guangzhou Hao Jia Ye Technology Co" },
		{/*  47, 0x2F, */ "Ming Xin Limited" },
		{/*  48, 0xB0, */ "Barefoot Networks" },
		{/*  49, 0x31, */ "Biwin Semiconductor (HK) Co Ltd" },
		{/*  50, 0x32, */ "UD INFO Corporation" },
		{/*  51, 0xB3, */ "Trek Technology (S) PTE Ltd" },
		{/*  52, 0x34, */ "Xiamen Kingblaze Technology Co Ltd" },
		{/*  53, 0xB5, */ "Shenzhen Lomica Technology Co Ltd" },
		{/*  54, 0xB6, */ "Nuclei System Technology Co Ltd" },
		{/*  55, 0x37, */ "Wuhan Xun Zhan Electronic Technology" },
		{/*  56, 0x38, */ "Shenzhen Ingacom Semiconductor Ltd" },
		{/*  57, 0xB9, */ "Zotac Technology Ltd" },
		{/*  58, 0xBA, */ "Foxline" },
		{/*  59, 0x3B, */ "Shenzhen Farasia Science Technology" },
		{/*  60, 0xBC, */ "Efinix Inc" },
		{/*  61, 0x3D, */ "Hua Nan San Xian Technology Co Ltd" },
		{/*  62, 0x3E, */ "Goldtech Electronics Co Ltd" },
		{/*  63, 0xBF, */ "Shanghai Han Rong Microelectronics Co" },
		{/*  64, 0x40, */ "Shenzhen Zhongguang Yunhe Trading" },
		{/*  65, 0xC1, */ "Smart Shine(QingDao) Microelectronics" },
		{/*  66, 0xC2, */ "Thermaltake Technology Co Ltd" },
		{/*  67, 0x43, */ "Shenzhen O’Yang Maile Technology Ltd" },
		{/*  68, 0xC4, */ "UPMEM" },
		{/*  69, 0x45, */ "Chun Well Technology Holding Limited" },
		{/*  70, 0x46, */ "Astera Labs Inc" },
		{/*  71, 0xC7, */ "Winconway" },
		{/*  72, 0xC8, */ "Advantech Co Ltd" },
		{/*  73, 0x49, */ "Chengdu Fengcai Electronic Technology" },
		{/*  74, 0x4A, */ "The Boeing Company" },
		{/*  75, 0xCB, */ "Blaize Inc" },
		{/*  76, 0x4C, */ "Ramonster Technology Co Ltd" },
		{/*  77, 0xCD, */ "Wuhan Naonongmai Technology Co Ltd" },
		{/*  78, 0xCE, */ "Shenzhen Hui ShingTong Technology" },
		{/*  79, 0x4F, */ "Yourlyon" },
		{/*  80, 0xD0, */ "Fabu Technology" },
		{/*  81, 0x51, */ "Shenzhen Yikesheng Technology Co Ltd" },
		{/*  82, 0x52, */ "NOR-MEM" },
		{/*  83, 0xD3, */ "Cervoz Co Ltd" },
		{/*  84, 0x54, */ "Bitmain Technologies Inc." },
		{/*  85, 0xD5, */ "Facebook Inc" },
		{/*  86, 0xD6, */ "Shenzhen Longsys Electronics Co Ltd" },
		{/*  87, 0x57, */ "Guangzhou Siye Electronic Technology" },
		{/*  88, 0x58, */ "Silergy" },
		{/*  89, 0xD9, */ "Adamway" },
		{/*  90, 0xDA, */ "PZG" },
		{/*  91, 0x5B, */ "Shenzhen King Power Electronics" },
		{/*  92, 0xDC, */ "Guangzhou ZiaoFu Tranding Co Ltd" },
		{/*  93, 0x5D, */ "Shenzhen SKIHOTAR Semiconductor" },
		{/*  94, 0x5E, */ "PulseRain Technology" },
		{/*  95, 0xDF, */ "Seeker Technology Limited" },
		{/*  96, 0xE0, */ "Shenzhen OSCOO Tech Co Ltd" },
		{/*  97, 0x61, */ "Shenzhen Yze Technology Co Ltd" },
		{/*  98, 0x62, */ "Shenzhen Jieshuo Electronic Commerce" },
		{/*  99, 0xE3, */ "Gazda" },
		{/* 100, 0x64, */ "Hua Wei Technology Co Ltd" },
		{/* 101, 0xE5, */ "Esperanto Technologies" },
		{/* 102, 0xE6, */ "JinSheng Electronic (Shenzhen) Co Ltd" },
		{/* 103, 0x67, */ "Shenzhen Shi Bolunshuai Technology" },
		{/* 104, 0x68, */ "Shanghai Rui Xuan Information Tech" },
		{/* 105, 0xE9, */ "Fraunhofer IIS" },
		{/* 106, 0xEA, */ "Kandou Bus SA" },
		{/* 107, 0x6B, */ "Acer" },
		{/* 108, 0xEC, */ "Artmem Technology Co Ltd" },
		{/* 109, 0x6D, */ "Gstar Semiconductor Co Ltd" },
		{/* 110, 0x6E, */ "ShineDisk" },
		{/* 111, 0xEF, */ "Shenzhen CHN Technology Co Ltd" },
		{/* 112, 0x70, */ "UnionChip Semiconductor Co Ltd" },
		{/* 113, 0xF1, */ "Tanbassh" },
		{/* 114, 0xF2, */ "Shenzhen Tianyu Jieyun Intl Logistics" },
		{/* 115, 0x73, */ "MCLogic Inc" },
		{/* 116, 0xF4, */ "Eorex Corporation" },
		{/* 117, 0x75, */ "Arm Technology (China) Co Ltd" },
		{/* 118, 0x76, */ "Lexar Co Limited" },
		{/* 119, 0xF7, */ "QinetiQ Group plc" },
		{/* 120, 0xF8, */ "Exascend" },
		{/* 121, 0x79, */ "Hong Kong Hyunion Electronics Co Ltd" },
		{/* 122, 0x7A, */ "Shenzhen Banghong Electronics Co Ltd" },
		{/* 123, 0xFB, */ "MBit Wireless Inc" },
		{/* 124, 0x7C, */ "Hex Five Security Inc" },
		{/* 125, 0xFD, */ "ShenZhen Juhor Precision Tech Co Ltd" },
		{/* 126, 0xFE, */ "Shenzhen Reeinno Technology Co Ltd" },
	},
	{ // bank #12
		{/*   1, 0x01, */ "ABIT Electronics (Shenzhen) Co Ltd"},
		{/*   2, 0x02, */ "Semidrive" },
		{/*   3, 0x83, */ "MyTek Electronics Corp" },
		{/*   4, 0x04, */ "Wxilicon Technology Co Ltd" },
		{/*   5, 0x85, */ "Shenzhen Meixin Electronics Ltd" },
		{/*   6, 0x86, */ "Ghost Wolf" },
		{/*   7, 0x07, */ "LiSion Technologies Inc" },
		{/*   8, 0x08, */ "Power Active Co Ltd" },
		{/*   9, 0x89, */ "Pioneer High Fidelity Taiwan Co. Ltd" },
		{/*  10, 0x8A, */ "LuoSilk" },
		{/*  11, 0x0B, */ "Shenzhen Chuangshifeida Technology" },
		{/*  12, 0x8C, */ "Black Sesame Technologies Inc" },
		{/*  13, 0x0D, */ "Jiangsu Xinsheng Intelligent Technology" },
		{/*  14, 0x0E, */ "MLOONG" },
		{/*  15, 0x8F, */ "Quadratica LLC" },
		{/*  16, 0x10, */ "Anpec Electronics" },
		{/*  17, 0x91, */ "Xi’an Morebeck Semiconductor Tech Co" },
		{/*  18, 0x92, */ "Kingbank Technology Co Ltd" },
		{/*  19, 0x13, */ "ITRenew Inc" },
		{/*  20, 0x94, */ "Shenzhen Eaget Innovation Tech Ltd" },
		{/*  21, 0x15, */ "Jazer" },
		{/*  22, 0x16, */ "Xiamen Semiconductor Investment Group" },
		{/*  23, 0x97, */ "Guangzhou Longdao Network Tech Co" },
		{/*  24, 0x98, */ "Shenzhen Futian SEC Electronic Market" },
		{/*  25, 0x19, */ "Allegro Microsystems LLC" },
		{/*  26, 0x1A, */ "Hunan RunCore Innovation Technology" },
		{/*  27, 0x9B, */ "C-Corsa Technology" },
		{/*  28, 0x1C, */ "Zhuhai Chuangfeixin Technology Co Ltd" },
		{/*  29, 0x9D, */ "Beijing InnoMem Technologies Co Ltd" },
		{/*  30, 0x9E, */ "YooTin" },
		{/*  31, 0x1F, */ "Shenzhen Pengxiong Technology Co Ltd" },
		{/*  32, 0x20, */ "Dongguan Yingbang Commercial Trading Co" },
		{/*  33, 0xA1, */ "Shenzhen Ronisys Electronics Co Ltd" },
		{/*  34, 0xA2, */ "Hongkong Xinlan Guangke Co Ltd" },
		{/*  35, 0x23, */ "Apex Microelectronics Co Ltd" },
		{/*  36, 0xA4, */ "Beijing Hongda Jinming Technology Co Ltd" },
		{/*  37, 0x25, */ "Ling Rui Technology (Shenzhen) Co Ltd" },
		{/*  38, 0x26, */ "Hongkong Hyunion Electronics Co Ltd" },
		{/*  39, 0xA7, */ "Starsystems Inc" },
		{/*  40, 0xA8, */ "Shenzhen Yingjiaxun Industrial Co Ltd" },
		{/*  41, 0x29, */ "Dongguan Crown Code Electronic Commerce" },
		{/*  42, 0x2A, */ "Monolithic Power Systems Inc" },
		{/*  43, 0xAB, */ "WuHan SenNaiBo E-Commerce Co Ltd" },
		{/*  44, 0x2C, */ "Hangzhou Hikstorage Technology Co" },
		{/*  45, 0xAD, */ "Shenzhen Goodix Technology Co Ltd" },
		{/*  46, 0xAE, */ "Aigo Electronic Technology Co Ltd" },
		{/*  47, 0x2F, */ "Hefei Konsemi Storage Technology Co Ltd" },
		{/*  48, 0xB0, */ "Cactus Technologies Limited" },
		{/*  49, 0x31, */ "DSIN" },
		{/*  50, 0x32, */ "Blu Wireless Technology" },
		{/*  51, 0xB3, */ "Nanjing UCUN Technology Inc" },
		{/*  52, 0x34, */ "Acacia Communications" },
		{/*  53, 0xB5, */ "Beijinjinshengyihe Technology Co Ltd" },
		{/*  54, 0xB6, */ "Zyzyx" },
		{/*  55, 0x37, */ "C-SKY Microsystems Co Ltd" },
		{/*  56, 0x38, */ "Shenzhen Hystou Technology Co Ltd" },
		{/*  57, 0xB9, */ "Syzexion" },
		{/*  58, 0xBA, */ "Kembona" },
		{/*  59, 0x3B, */ "Qingdao Thunderobot Technology Co Ltd" },
		{/*  60, 0xBC, */ "Morse Micro" },
		{/*  61, 0x3D, */ "Shenzhen Envida Technology Co Ltd" },
		{/*  62, 0x3E, */ "UDStore Solution Limited" },
		{/*  63, 0xBF, */ "Shunlie" },
		{/*  64, 0x40, */ "Shenzhen Xin Hong Rui Tech Ltd" },
		{/*  65, 0xC1, */ "Shenzhen Yze Technology Co Ltd" },
		{/*  66, 0xC2, */ "Shenzhen Huang Pu He Xin Technology" },
		{/*  67, 0x43, */ "Xiamen Pengpai Microelectronics Co Ltd" },
		{/*  68, 0xC4, */ "JISHUN" },
		{/*  69, 0x45, */ "Shenzhen WODPOSIT Technology Co" },
		{/*  70, 0x46, */ "Unistar" },
		{/*  71, 0xC7, */ "UNICORE Electronic (Suzhou) Co Ltd" },
		{/*  72, 0xC8, */ "Axonne Inc" },
		{/*  73, 0x49, */ "Shenzhen SOVERECA Technology Co" },
		{/*  74, 0x4A, */ "Dire Wolf" },
		{/*  75, 0xCB, */ "Whampoa Core Technology Co Ltd" },
		{/*  76, 0x4C, */ "CSI Halbleiter GmbH" },
		{/*  77, 0xCD, */ "ONE Semiconductor" },
		{/*  78, 0xCE, */ "SimpleMachines Inc" },
		{/*  79, 0x4F, */ "Shenzhen Chengyi Qingdian Electronic" },
		{/*  80, 0xD0, */ "Shenzhen Xinlianxin Network Technology" },
		{/*  81, 0x51, */ "Vayyar Imaging Ltd" },
		{/*  82, 0x52, */ "Paisen Network Technology Co Ltd" },
		{/*  83, 0xD3, */ "Shenzhen Fengwensi Technology Co Ltd" },
		{/*  84, 0x54, */ "Caplink Technology Limited" },
		{/*  85, 0xD5, */ "JJT Solution Co Ltd" },
		{/*  86, 0xD6, */ "HOSIN Global Electronics Co Ltd" },
		{/*  87, 0x57, */ "Shenzhen KingDisk Century Technology" },
		{/*  88, 0x58, */ "SOYO" },
		{/*  89, 0xD9, */ "DIT Technology Co Ltd" },
		{/*  90, 0xDA, */ "iFound" },
		{/*  91, 0x5B, */ "Aril Computer Company" },
		{/*  92, 0xDC, */ "ASUS" },
		{/*  93, 0x5D, */ "Shenzhen Ruiyingtong Technology Co" },
		{/*  94, 0x5E, */ "HANA Micron" },
		{/*  95, 0xDF, */ "RANSOR" },
		{/*  96, 0xE0, */ "Axiado Corporation" },
		{/*  97, 0x61, */ "Tesla Corporation" },
		{/*  98, 0x62, */ "Pingtouge (Shanghai) Semiconductor Co" },
		{/*  99, 0xE3, */ "S3Plus Technologies SA" },
		{/* 100, 0x64, */ "Integrated Silicon Solution Israel Ltd" },
		{/* 101, 0xE5, */ "GreenWaves Technologies" },
		{/* 102, 0xE6, */ "NUVIA Inc" },
		{/* 103, 0x67, */ "Guangzhou Shuvrwine Technology Co" },
		{/* 104, 0x68, */ "Shenzhen Hangshun Chip Technology" },
		{/* 105, 0xE9, */ "Chengboliwei Electronic Business" },
		{/* 106, 0xEA, */ "Kowin Technology HK Limited" },
		{/* 107, 0x6B, */ "Euronet Technology Inc" },
		{/* 108, 0xEC, */ "SCY" },
		{/* 109, 0x6D, */ "Shenzhen Xinhongyusheng Electrical" },
		{/* 110, 0x6E, */ "PICOCOM" },
		{/* 111, 0xEF, */ "Shenzhen Toooogo Memory Technology" },
		{/* 112, 0x70, */ "VLSI Solution" },
		{/* 113, 0xF1, */ "Costar Electronics Inc" },
		{/* 114, 0xF2, */ "Shenzhen Huatop Technology Co Ltd" },
		{/* 115, 0x73, */ "Inspur Electronic Information Industry" },
		{/* 116, 0xF4, */ "Shenzhen Boyuan Computer Technology" },
		{/* 117, 0x75, */ "Beijing Welldisk Electronics Co Ltd" },
		{/* 118, 0x76, */ "Suzhou EP Semicon Co Ltd" },
		{/* 119, 0xF7, */ "Zhejiang Dahua Memory Technology" },
		{/* 120, 0xF8, */ "Virtu Financial" },
		{/* 121, 0x79, */ "Datotek International Co Ltd" },
		{/* 122, 0x7A, */ "Telecom and Microelectronics Industries" },
		{/* 123, 0xFB, */ "Echow Technology Ltd" },
		{/* 124, 0x7C, */ "APEX-INFO" },
		{/* 125, 0xFD, */ "Yingpark" },
		{/* 126, 0xFE, */ "Shenzhen Bigway Tech Co Ltd" },
	},
	{ // bank #13
		{/*   1, 0x01, */ "Beijing Haawking Technology Co Ltd"},
		{/*   2, 0x02, */ "Open HW Group" },
		{/*   3, 0x83, */ "JHICC" },
		{/*   4, 0x04, */ "ncoder AG" },
		{/*   5, 0x85, */ "ThinkTech Information Technology Co" },
		{/*   6, 0x86, */ "Shenzhen Chixingzhe Technology Co Ltd" },
		{/*   7, 0x07, */ "Biao Ram Technology Co Ltd" },
		{/*   8, 0x08, */ "Shenzhen Kaizhuoyue Electronics Co Ltd" },
		{/*   9, 0x89, */ "Shenzhen YC Storage Technology Co Ltd" },
		{/*  10, 0x8A, */ "Shenzhen Chixingzhe Technology Co" },
		{/*  11, 0x0B, */ "Wink Semiconductor (Shenzhen) Co Ltd" },
		{/*  12, 0x8C, */ "AISTOR" },
		{/*  13, 0x0D, */ "Palma Ceia SemiDesign" },
		{/*  14, 0x0E, */ "EM Microelectronic-Marin SA" },
		{/*  15, 0x8F, */ "Shenzhen Monarch Memory Technology" },
		{/*  16, 0x10, */ "Reliance Memory Inc" },
		{/*  17, 0x91, */ "Jesis" },
		{/*  18, 0x92, */ "Espressif Systems (Shanghai) Co Ltd" },
		{/*  19, 0x13, */ "Shenzhen Sati Smart Technology Co Ltd" },
		{/*  20, 0x94, */ "NeuMem Co Ltd" },
		{/*  21, 0x15, */ "Lifelong" },
		{/*  22, 0x16, */ "Beijing Oitech Technology Co Ltd" },
		{/*  23, 0x97, */ "Groupe LDLC" },
		{/*  24, 0x98, */ "Semidynamics Technology Services SLU" },
		{/*  25, 0x19, */ "swordbill" },
		{/*  26, 0x1A, */ "YIREN" },
		{/*  27, 0x9B, */ "Shenzhen Yinxiang Technology Co Ltd" },
		{/*  28, 0x1C, */ "PoweV Electronic Technology Co Ltd" },
		{/*  29, 0x9D, */ "LEORICE" },
		{/*  30, 0x9E, */ "Waymo LLC" },
		{/*  31, 0x1F, */ "Ventana Micro Systems" },
		{/*  32, 0x20, */ "Hefei Guangxin Microelectronics Co Ltd" },
		{/*  33, 0xA1, */ "Shenzhen Sooner Industrial Co Ltd" },
		{/*  34, 0xA2, */ "Horizon Robotics" },
		{/*  35, 0x23, */ "Tangem AG" },
		{/*  36, 0xA4, */ "FuturePath Technology (Shenzhen) Co" },
		{/*  37, 0x25, */ "RC Module" },
		{/*  38, 0x26, */ "Timetec International Inc" },
		{/*  39, 0xA7, */ "ICMAX Technologies Co Limited" },
		{/*  40, 0xA8, */ "Lynxi Technologies Ltd Co" },
		{/*  41, 0x29, */ "Guangzhou Taisupanke Computer Equipment" },
		{/*  42, 0x2A, */ "Ceremorphic Inc" },
		{/*  43, 0xAB, */ "Biwin Storage Technology Co Ltd" },
		{/*  44, 0x2C, */ "Beijing ESWIN Computing Technology" },
		{/*  45, 0xAD, */ "WeForce Co Ltd" },
		{/*  46, 0xAE, */ "Shenzhen Fanxiang Information Technology" },
		{/*  47, 0x2F, */ "Unisoc" },
		{/*  48, 0xB0, */ "YingChu" },
		{/*  49, 0x31, */ "GUANCUN" },
		{/*  50, 0x32, */ "IPASON" },
		{/*  51, 0xB3, */ "Ayar Labs" },
		{/*  52, 0x34, */ "Amazon" },
		{/*  53, 0xB5, */ "Shenzhen Xinxinshun Technology Co" },
		{/*  54, 0xB6, */ "Galois Inc" },
		{/*  55, 0x37, */ "Ubilite Inc" },
		{/*  56, 0x38, */ "Shenzhen Quanxing Technology Co Ltd" },
		{/*  57, 0xB9, */ "Group RZX Technology LTDA" },
		{/*  58, 0xBA, */ "Yottac Technology (XI’AN) Cooperation" },
		{/*  59, 0x3B, */ "Shenzhen RuiRen Technology Co Ltd" },
		{/*  60, 0xBC, */ "Group Star Technology Co Ltd" },
		{/*  61, 0x3D, */ "RWA (Hong Kong) Ltd" },
		{/*  62, 0x3E, */ "Genesys Logic Inc" },
		{/*  63, 0xBF, */ "T3 Robotics Inc." },
		{/*  64, 0x40, */ "Biostar Microtech International Corp" },
		{/*  65, 0xC1, */ "Shenzhen SXmicro Technology Co Ltd" },
		{/*  66, 0xC2, */ "Shanghai Yili Computer Technology Co" },
		{/*  67, 0x43, */ "Zhixin Semicoducotor Co Ltd" },
		{/*  68, 0xC4, */ "uFound" },
		{/*  69, 0x45, */ "Aigo Data Security Technology Co. Ltd" },
		{/*  70, 0x46, */ ".GXore Technologies" },
		{/*  71, 0xC7, */ "Shenzhen Pradeon Intelligent Technology" },
		{/*  72, 0xC8, */ "Power LSI" },
		{/*  73, 0x49, */ "PRIME" },
		{/*  74, 0x4A, */ "Shenzhen Juyang Innovative Technology" },
		{/*  75, 0xCB, */ "CERVO" },
		{/*  76, 0x4C, */ "SiEngine Technology Co., Ltd." },
		{/*  77, 0xCD, */ "Beijing Unigroup Tsingteng MicroSystem" },
		{/*  78, 0xCE, */ "Brainsao GmbH" },
		{/*  79, 0x4F, */ "Credo Technology Group Ltd" },
		{/*  80, 0xD0, */ "Shanghai Biren Technology Co Ltd" },
		{/*  81, 0x51, */ "Nucleu Semiconductor" },
		{/*  82, 0x52, */ "Shenzhen Guangshuo Electronics Co Ltd" },
		{/*  83, 0xD3, */ "ZhongsihangTechnology Co Ltd" },
		{/*  84, 0x54, */ "Suzhou Mainshine Electronic Co Ltd." },
		{/*  85, 0xD5, */ "Guangzhou Riss Electronic Technology" },
		{/*  86, 0xD6, */ "Shenzhen Cloud Security Storage Co" },
		{/*  87, 0x57, */ "ROG" },
		{/*  88, 0x58, */ "Perceive" },
		{/*  89, 0xD9, */ "e-peas" },
		{/*  90, 0xDA, */ "Fraunhofer IPMS" },
		{/*  91, 0x5B, */ "Shenzhen Daxinlang Electronic Tech Co" },
		{/*  92, 0xDC, */ "Abacus Peripherals Private Limited" },
		{/*  93, 0x5D, */ "OLOy Technology" },
		{/*  94, 0x5E, */ "Wuhan P&S Semiconductor Co Ltd" },
		{/*  95, 0xDF, */ "Sitrus Technology" },
		{/*  96, 0xE0, */ "AnHui Conner Storage Co Ltd" },
		{/*  97, 0x61, */ "Rochester Electronics" },
		{/*  98, 0x62, */ "Wuxi Smart Memories Technologies Co" },
		{/*  99, 0xE3, */ "Star Memory" },
		{/* 100, 0x64, */ "Agile Memory Technology Co Ltd" },
		{/* 101, 0xE5, */ "MEJEC" },
		{/* 102, 0xE6, */ "Rockchip Electronics Co Ltd" },
		{/* 103, 0x67, */ "Dongguan Guanma e-commerce Co Ltd" },
		{/* 104, 0x68, */ "Rayson Hi-Tech (SZ) Limited" },
		{/* 105, 0xE9, */ "MINRES Technologies GmbH" },
		{/* 106, 0xEA, */ "Himax Technologies Inc" },
		{/* 107, 0x6B, */ "Shenzhen Cwinner Technology Co Ltd" },
		{/* 108, 0xEC, */ "Tecmiyo" },
		{/* 109, 0x6D, */ "Shenzhen Suhuicun Technology Co Ltd" },
		{/* 110, 0x6E, */ "Vickter Electronics Co. Ltd." },
		{/* 111, 0xEF, */ "lowRISC" },
		{/* 112, 0x70, */ "EXEGate FZE" },
		{/* 113, 0xF1, */ "Shenzhen 9 Chapter Technologies Co" },
		{/* 114, 0xF2, */ "Addlink" },
		{/* 115, 0x73, */ "Starsway" },
		{/* 116, 0xF4, */ "Pensando Systems Inc." },
		{/* 117, 0x75, */ "AirDisk" },
		{/* 118, 0x76, */ "Shenzhen Speedmobile Technology Co" },
		{/* 119, 0xF7, */ "PEZY Computing" },
		{/* 120, 0xF8, */ "Extreme Engineering Solutions Inc" },
		{/* 121, 0x79, */ "Shangxin Technology Co Ltd" },
		{/* 122, 0x7A, */ "Shanghai Zhaoxin Semiconductor Co" },
		{/* 123, 0xFB, */ "Xsight Labs Ltd" },
		{/* 124, 0x7C, */ "Hangzhou Hikstorage Technology Co" },
		{/* 125, 0xFD, */ "Dell Technologies" },
		{/* 126, 0xFE, */ "Guangdong StarFive Technology Co" },
	},
	{ // bank #14
		{/*   1, 0x01, */ "TECOTON"},
		{/*   2, 0x02, */ "Abko Co Ltd" },
		{/*   3, 0x83, */ "Shenzhen Feisrike Technology Co Ltd" },
		{/*   4, 0x04, */ "Shenzhen Sunhome Electronics Co Ltd" },
		{/*   5, 0x85, */ "Global Mixed-mode Technology Inc" },
		{/*   6, 0x86, */ "Shenzhen Weien Electronics Co Ltd." },
		{/*   7, 0x07, */ "Shenzhen Cooyes Technology Co Ltd" },
		{/*   8, 0x08, */ "ShenZhen ChaoYing ZhiNeng Technology" },
		{/*   9, 0x89, */ "E-Rockic Technology Company Limited" },
		{/*  10, 0x8A, */ "Aerospace Science Memory Shenzhen" },
		{/*  11, 0x0B, */ "Shenzhen Quanji Technology Co Ltd" },
		{/*  12, 0x8C, */ "Dukosi" },
		{/*  13, 0x0D, */ "Maxell Corporation of America" },
		{/*  14, 0x0E, */ "Shenshen Xinxintao Electronics Co Ltd" },
		{/*  15, 0x8F, */ "Zhuhai Sanxia Semiconductor Co Ltd" },
		{/*  16, 0x10, */ "Groq Inc" },
		{/*  17, 0x91, */ "AstraTek" },
		{/*  18, 0x92, */ "Shenzhen Xinyuze Technology Co Ltd" },
		{/*  19, 0x13, */ "All Bit Semiconductor" },
		{/*  20, 0x94, */ "ACFlow" },
		{/*  21, 0x15, */ "Shenzhen Sipeed Technology Co Ltd" },
		{/*  22, 0x16, */ "Linzhi Hong Kong Co Limited" },
		{/*  23, 0x97, */ "Supreme Wise Limited" },
		{/*  24, 0x98, */ "Blue Cheetah Analog Design Inc" },
		{/*  25, 0x19, */ "Hefei Laiku Technology Co Ltd" },
		{/*  26, 0x1A, */ "Zord" },
		{/*  27, 0x9B, */ "SBO Hearing A/S" },
		{/*  28, 0x1C, */ "Regent Sharp International Limited" },
		{/*  29, 0x9D, */ "Permanent Potential Limited" },
		{/*  30, 0x9E, */ "Creative World International Limited" },
		{/*  31, 0x1F, */ "Base Creation International Limited" },
		{/*  32, 0x20, */ "Shenzhen Zhixin Chuanglian Technology" },
		{/*  33, 0xA1, */ "Protected Logic Corporation" },
		{/*  34, 0xA2, */ "Sabrent" },
		{/*  35, 0x23, */ "Union Memory" },
		{/*  36, 0xA4, */ "NEUCHIPS Corporation" },
		{/*  37, 0x25, */ "Ingenic Semiconductor Co Ltd" },
		{/*  38, 0x26, */ "SiPearl" },
		{/*  39, 0xA7, */ "Shenzhen Actseno Information Technology" },
		{/*  40, 0xA8, */ "RIVAI Technologies (Shenzhen) Co Ltd" },
		{/*  41, 0x29, */ "Shenzhen Sunny Technology Co Ltd" },
		{/*  42, 0x2A, */ "Cott Electronics Ltd" },
		{/*  43, 0xAB, */ "Shanghai Synsense Technologies Co Ltd" },
		{/*  44, 0x2C, */ "Shenzhen Jintang Fuming Optoelectronics" },
		{/*  45, 0xAD, */ "CloudBEAR LLC" },
		{/*  46, 0xAE, */ "Emzior, LLC" },
		{/*  47, 0x2F, */ "Ehiway Microelectronic Science Tech Co" },
		{/*  48, 0xB0, */ "UNIM Innovation Technology (Wu XI)" },
		{/*  49, 0x31, */ "GDRAMARS" },
		{/*  50, 0x32, */ "Meminsights Technology" },
		{/*  51, 0xB3, */ "Zhuzhou Hongda Electronics Corp Ltd" },
		{/*  52, 0x34, */ "Luminous Computing Inc" },
		{/*  53, 0xB5, */ "PROXMEM" },
		{/*  54, 0xB6, */ "Draper Labs" },
		{/*  55, 0x37, */ "ORICO Technologies Co. Ltd." },
		{/*  56, 0x38, */ "Space Exploration Technologies Corp" },
		{/*  57, 0xB9, */ "AONDEVICES Inc" },
		{/*  58, 0xBA, */ "Shenzhen Netforward Micro Electronic" },
		{/*  59, 0x3B, */ "Syntacore Ltd" },
		{/*  60, 0xBC, */ "Shenzhen Secmem Microelectronics Co" },
		{/*  61, 0x3D, */ "ONiO As" },
		{/*  62, 0x3E, */ "Shenzhen Peladn Technology Co Ltd" },
		{/*  63, 0xBF, */ "O-Cubes Shanghai Microelectronics" },
		{/*  64, 0x40, */ "ASTC" },
		{/*  65, 0xC1, */ "UMIS" },
		{/*  66, 0xC2, */ "Paradromics" },
		{/*  67, 0x43, */ "Sinh Micro Co Ltd" },
		{/*  68, 0xC4, */ "Metorage Semiconductor Technology Co" },
		{/*  69, 0x45, */ "Aeva Inc" },
		{/*  70, 0x46, */ "HongKong Hyunion Electronics Co Ltd" },
		{/*  71, 0xC7, */ "China Flash Co Ltd" },
		{/*  72, 0xC8, */ "Sunplus Technology Co Ltd" },
		{/*  73, 0x49, */ "Idaho Scientific" },
		{/*  74, 0x4A, */ "Suzhou SF Micro Electronics Co Ltd" },
		{/*  75, 0xCB, */ "IMEX Cap AG" },
		{/*  76, 0x4C, */ "Fitipower Integrated Technology Co Ltd" },
		{/*  77, 0xCD, */ "ShenzhenWooacme Technology Co Ltd" },
		{/*  78, 0xCE, */ "KeepData Original Chips" },
		{/*  79, 0x4F, */ "Rivos Inc" },
		{/*  80, 0xD0, */ "Big Innovation Company Limited" },
		{/*  81, 0x51, */ "Wuhan YuXin Semiconductor Co Ltd" },
		{/*  82, 0x52, */ "United Memory Technology (Jiangsu)" },
		{/*  83, 0xD3, */ "PQShield Ltd" },
		{/*  84, 0x54, */ "ArchiTek Corporation" },
		{/*  85, 0xD5, */ "ShenZhen AZW Technology Co Ltd" },
		{/*  86, 0xD6, */ "Hengchi Zhixin (Dongguan) Technology" },
		{/*  87, 0x57, */ "Eggtronic Engineering Spa" },
		{/*  88, 0x58, */ "Fusontai Technology" },
		{/*  89, 0xD9, */ "PULP Platform" },
		{/*  90, 0xDA, */ "Koitek Electronic Technology (Shenzhen) Co" },
		{/*  91, 0x5B, */ "Shenzhen Jiteng Network Technology Co" },
		{/*  92, 0xDC, */ "Aviva Links Inc" },
		{/*  93, 0x5D, */ "Trilinear Technologies Inc" },
		{/*  94, 0x5E, */ "Shenzhen Developer Microelectronics Co" },
		{/*  95, 0xDF, */ "Guangdong OPPO Mobile Telecommunication" },
		{/*  96, 0xE0, */ "Akeana" },
		{/*  97, 0x61, */ "Lyczar" },
		{/*  98, 0x62, */ "Shenzhen Qiji Technology Co Ltd" },
		{/*  99, 0xE3, */ "Shenzhen Shangzhaoyuan Technology" },
		{/* 100, 0x64, */ "Han Stor" },
		{/* 101, 0xE5, */ "China Micro Semicon Co., Ltd." },
		{/* 102, 0xE6, */ "Shenzhen Zhuqin Technology Co Ltd" },
		{/* 103, 0x67, */ "Shanghai Ningyuan Electronic Technology" },
		{/* 104, 0x68, */ "Auradine" },
		{/* 105, 0xE9, */ "Suzhou Yishuo Electronics Co Ltd" },
		{/* 106, 0xEA, */ "Faurecia Clarion Electronics" },
		{/* 107, 0x6B, */ "SiMa Technologies" },
		{/* 108, 0xEC, */ "CFD Sales Inc" },
		{/* 109, 0x6D, */ "Suzhou Comay Information Co Ltd" },
		{/* 110, 0x6E, */ "Yentek" },
		{/* 111, 0xEF, */ "Qorvo Inc" },
		{/* 112, 0x70, */ "Shenzhen Youzhi Computer Technology" },
		{/* 113, 0xF1, */ "Sychw Technology (Shenzhen) Co Ltd" },
		{/* 114, 0xF2, */ "MK Founder Technology Co Ltd" },
		{/* 115, 0x73, */ "Siliconwaves Technologies Co Ltd" },
		{/* 116, 0xF4, */ "Hongkong Hyunion Electronics Co Ltd" },
		{/* 117, 0x75, */ "Shenzhen Xinxinzhitao Electronics Business" },
		{/* 118, 0x76, */ "Shenzhen HenQi Electronic Commerce Co" },
		{/* 119, 0xF7, */ "Shenzhen Jingyi Technology Co Ltd" },
		{/* 120, 0xF8, */ "Xiaohua Semiconductor Co. Ltd." },
		{/* 121, 0x79, */ "Shenzhen Dalu Semiconductor Technology" },
		{/* 122, 0x7A, */ "Shenzhen Ninespeed Electronics Co Ltd" },
		{/* 123, 0xFB, */ "ICYC Semiconductor Co Ltd" },
		{/* 124, 0x7C, */ "Shenzhen Jaguar Microsystems Co Ltd" },
		{/* 125, 0xFD, */ "Beijing EC-Founder Co Ltd" },
		{/* 126, 0xFE, */ "Shenzhen Taike Industrial Automation Co" },
	},
	{ // bank #15
		{/*   1, 0x01, */ "Kalray SA"},
		{/*   2, 0x02, */ "Shanghai Iluvatar CoreX Semiconductor Co" },
		{/*   3, 0x83, */ "Fungible Inc" },
		{/*   4, 0x04, */ "Song Industria E Comercio de Eletronicos" },
		{/*   5, 0x85, */ "DreamBig Semiconductor Inc" },
		{/*   6, 0x86, */ "ChampTek Electronics Corp" },
		{/*   7, 0x07, */ "Fusontai Technology" },
		{/*   8, 0x08, */ "Endress Hauser AG" },
		{/*   9, 0x89, */ "altec ComputerSysteme GmbH" },
		{/*  10, 0x8A, */ "UltraRISC Technology (Shanghai) Co Ltd" },
		{/*  11, 0x0B, */ "Shenzhen Jing Da Kang Technology Co Ltd" },
		{/*  12, 0x8C, */ "Hangzhou Hongjun Microelectronics Co Ltd" },
		{/*  13, 0x0D, */ "Pliops Ltd" },
		{/*  14, 0x0E, */ "Cix Technology (Shanghai) Co Ltd" },
		{/*  15, 0x8F, */ "TeraDevices Inc" },
		{/*  16, 0x10, */ "SpacemiT (Hangzhou)Technology Co Ltd" },
		{/*  17, 0x91, */ "InnoPhase loT Inc" },
		{/*  18, 0x92, */ "InnoPhase loT Inc" },
		{/*  19, 0x13, */ "Yunhight Microelectronics" },
		{/*  20, 0x94, */ "Samnix" },
		{/*  21, 0x15, */ "HKC Storage Co Ltd" },
		{/*  22, 0x16, */ "Chiplego Technology (Shanghai) Co Ltd" },
		{/*  23, 0x97, */ "StoreSkill" },
		{/*  24, 0x98, */ "Shenzhen Astou Technology Company" },
		{/*  25, 0x19, */ "Guangdong LeafFive Technology Limited" },
		{/*  26, 0x1A, */ "Jin JuQuan" },
		{/*  27, 0x9B, */ "Huaxuan Technology (Shenzhen) Co Ltd" },
		{/*  28, 0x1C, */ "Gigastone Corporation" },
		{/*  29, 0x9D, */ "Kinsotin" },
		{/*  30, 0x9E, */ "PengYing" },
		{/*  31, 0x1F, */ "Shenzhen Xunhi Technology Co Ltd" },
		{/*  32, 0x20, */ "FOXX Storage Inc" },
		{/*  33, 0xA1, */ "Shanghai Belling Corporation Ltd" },
		{/*  34, 0xA2, */ "Glenfy Tech Co Ltd" },
		{/*  35, 0x23, */ "Sahasra Semiconductors Pvt Ltd" },
		{/*  36, 0xA4, */ "Chongqing SeekWave Technology Co Ltd" },
		{/*  37, 0x25, */ "Shenzhen Zhixing Intelligent Manufacturing" },
		{/*  38, 0x26, */ "Ethernovia" },
		{/*  39, 0xA7, */ "Shenzhen Xinrongda Technology Co Ltd" },
		{/*  40, 0xA8, */ "Hangzhou Clounix Technology Limited" },
		{/*  41, 0x29, */ "JGINYUE" },
		{/*  42, 0x2A, */ "Shenzhen Xinwei Semiconductor Co Ltd" },
		{/*  43, 0xAB, */ "COLORFIRE Technology Co Ltd" },
		{/*  44, 0x2C, */ "B LKE" },
		{/*  45, 0xAD, */ "ZHUDIAN" },
		{/*  46, 0xAE, */ "REECHO" },
		{/*  47, 0x2F, */ "Enphase Energy Inc" },
		{/*  48, 0xB0, */ "Shenzhen Yingrui Storage Technology Co Ltd" },
		{/*  49, 0x31, */ "Shenzhen Sinomos Semiconductor Technology" },
		{/*  50, 0x32, */ "O2micro International Limited" },
		{/*  51, 0xB3, */ "Axelera AI BV" },
		{/*  52, 0x34, */ "Silicon Legend Technology (Suzhou) Co Ltd" },
		{/*  53, 0xB5, */ "Suzhou Novosense Microelectronics Co Ltd" },
		{/*  54, 0xB6, */ "Pirateman" },
		{/*  55, 0x37, */ "Yangtze MasonSemi" },
		{/*  56, 0x38, */ "Shanghai Yunsilicon Technology Co Ltd" },
		{/*  57, 0xB9, */ "Rayson" },
		{/*  58, 0xBA, */ "Alphawave IP" },
		{/*  59, 0x3B, */ "Shenzhen Visions Chip Electronic Technology" },
		{/*  60, 0xBC, */ "KYO Group" },
		{/*  61, 0x3D, */ "Shenzhen Aboison Technology Co Ltd" },
		{/*  62, 0x3E, */ "Shenzhen JingSheng Semiconducto Co Ltd" },
		{/*  63, 0xBF, */ "Shenzhen Dingsheng Technology Co Ltd" },
		{/*  64, 0x40, */ "EVAS Intelligence Co Ltd" },
		{/*  65, 0xC1, */ "Kaibright Electronic Technologies" },
		{/*  66, 0xC2, */ "Fraunhofer IMS" },
		{/*  67, 0x43, */ "Shenzhen Xinrui Renhe Technology" },
		{/*  68, 0xC4, */ "Beijing Vcore Technology Co Ltd" },
		{/*  69, 0x45, */ "Silicon Innovation Technologies Co Ltd" },
		{/*  70, 0x46, */ "Shenzhen Zhengxinda Technology Co Ltd" },
		{/*  71, 0xC7, */ "Shenzhen Remai Electronics Co Lttd" },
		{/*  72, 0xC8, */ "Shenzhen Xinruiyan Electronics Co Ltd" },
		{/*  73, 0x49, */ "CEC Huada Electronic Design Co Ltd" },
		{/*  74, 0x4A, */ "Westberry Technology Inc" },
		{/*  75, 0xCB, */ "Tongxin Microelectronics Co Ltd" },
		{/*  76, 0x4C, */ "UNIM Semiconductor (Shang Hai) Co Ltd" },
		{/*  77, 0xCD, */ "Shenzhen Qiaowenxingyu Industrial Co Ltd" },
		{/*  78, 0xCE, */ "ICC" },
		{/*  79, 0x4F, */ "Enfabrica Corporation" },
		{/*  80, 0xD0, */ "Niobium Microsystems Inc" },
		{/*  81, 0x51, */ "Xiaoli AI Electronics (Shenzhen) Co Ltd" },
		{/*  82, 0x52, */ "Silicon Mitus" },
		{/*  83, 0xD3, */ "Ajiatek Inc" },
		{/*  84, 0x54, */ "HomeNet" },
		{/*  85, 0xD5, */ "Shenzhen Shubang Technology Co Ltd" },
		{/*  86, 0xD6, */ "Exacta Technologies Ltd" },
		{/*  87, 0x57, */ "Synology" },
		{/*  88, 0x58, */ "Trium Elektronik Bilgi Islem San Ve Dis" },
		{/*  89, 0xD9, */ "Wuxi HippStor Technology Co Ltd" },
		{/*  90, 0xDA, */ "SSCT" },
		{/*  91, 0x5B, */ "Sichuan Heentai Semiconductor Co Ltd" },
		{/*  92, 0xDC, */ "Zhejiang University" },
		{/*  93, 0x5D, */ "www.shingroup.cn" },
		{/*  94, 0x5E, */ "Suzhou Nano Mchip Technology Company" },
		{/*  95, 0xDF, */ "Feature Integration Technology Inc" },
		{/*  96, 0xE0, */ "d-Matrix" },
		{/*  97, 0x61, */ "Golden Memory" },
		{/*  98, 0x62, */ "Qingdao Thunderobot Technology Co Ltd" },
		{/*  99, 0xE3, */ "Shenzhen Tianxiang Chuangxin Technology" },
		{/* 100, 0x64, */ "HYPHY USA" },
		{/* 101, 0xE5, */ "Valkyrie" },
		{/* 102, 0xE6, */ "Suzhou Hesetc Electronic Technology Co" },
		{/* 103, 0x67, */ "Hainan Zhongyuncun Technology Co Ltd" },
		{/* 104, 0x68, */ "Shenzhen Yousheng Bona Technology Co" },
		{/* 105, 0xE9, */ "Shenzhen Xinle Chuang Technology Co" },
		{/* 106, 0xEA, */ "DEEPX" },
		{/* 107, 0x6B, */ "iStarChip CA LLC" },
		{/* 108, 0xEC, */ "Shenzhen Vinreada Technology Co Ltd" },
		{/* 109, 0x6D, */ "Novatek Microelectronics Corp" },
		{/* 110, 0x6E, */ "Chemgdu EG Technology Co Ltd" },
		{/* 111, 0xEF, */ "AGI Technology" },
		{/* 112, 0x70, */ "Syntiant" },
		{/* 113, 0xF1, */ "AOC" },
		{/* 114, 0xF2, */ "GamePP" },
		{/* 115, 0x73, */ "Yibai Electronic Technologies" },
		{/* 116, 0xF4, */ "Hangzhou Rencheng Trading Co Ltd" },
		{/* 117, 0x75, */ "HOGE Technology Co Ltd" },
		{/* 118, 0x76, */ "United Micro Technology (Shenzhen) Co" },
		{/* 119, 0xF7, */ "Fabric of Truth Inc" },
		{/* 120, 0xF8, */ "Epitech" },
		{/* 121, 0x79, */ "Elitestek" },
		{/* 122, 0x7A, */ "Cornelis Networks Inc" },
		{/* 123, 0xFB, */ "WingSemi Technologies Co Ltd" },
		{/* 124, 0x7C, */ "ForwardEdge ASIC" },
		{/* 125, 0xFD, */ "Beijing Future Signet Technology Co Ltd" },
		{/* 126, 0xFE, */ "Fine Made Microelectronics Group Co Ltd" },
	},
	{ // bank #16
		{/*   1, 0x01, */ "Changxin Memory Technology (Shanghai)"},
		{/*   2, 0x02, */ "Synconv" },
		{/*   3, 0x83, */ "MULTIUNIT" },
		{/*   4, 0x04, */ "Zero ASIC Corporation" },
		{/*   5, 0x85, */ "NTT Innovative Devices Corporation" },
		{/*   6, 0x86, */ "Xbstor" },
		{/*   7, 0x07, */ "Shenzhen South Electron Co Ltd" },
		{/*   8, 0x08, */ "Iontra Inc" },
		{/*   9, 0x89, */ "SIEFFI Inc" },
		{/*  10, 0x8A, */ "HK Winston Electronics Co Limited" },
		{/*  11, 0x0B, */ "Anhui SunChip Semiconductor Technology" },
		{/*  12, 0x8C, */ "HaiLa Technologies Inc" },
		{/*  13, 0x0D, */ "AUTOTALKS" },
		{/*  14, 0x0E, */ "Shenzhen Ranshuo Technology Co Limited" },
		{/*  15, 0x8F, */ "ScaleFlux" },
		{/*  16, 0x10, */ "XC Memory" },
		{/*  17, 0x91, */ "Guangzhou Beimu Technology Co., Ltd" },
		{/*  18, 0x92, */ "Rays Semiconductor Nanjing Co Ltd" },
		{/*  19, 0x13, */ "Milli-Centi Intelligence Technology Jiangsu" },
		{/*  20, 0x94, */ "Zilia Technologies" },
		{/*  21, 0x15, */ "Incore Semiconductors" },
		{/*  22, 0x16, */ "Kinetic Technologies" },
		{/*  23, 0x97, */ "Nanjing Houmo Technology Co Ltd" },
		{/*  24, 0x98, */ "Suzhou Yige Technology Co Ltd" },
		{/*  25, 0x19, */ "Shenzhen Techwinsemi Technology Co Ltd" },
		{/*  26, 0x1A, */ "Pure Array Technology (Shanghai) Co. Ltd" },
		{/*  27, 0x9B, */ "Shenzhen Techwinsemi Technology Udstore" },
		{/*  28, 0x1C, */ "RISE MODE" },
		{/*  29, 0x9D, */ "NEWREESTAR" },
		{/*  30, 0x9E, */ "Hangzhou Hualan Microeletronique Co Ltd" },
		{/*  31, 0x1F, */ "Senscomm Semiconductor Co Ltd" },
		{/*  32, 0x20, */ "Holt Integrated Circuits" },
		{/*  33, 0xA1, */ "Tenstorrent Inc" },
		{/*  34, 0xA2, */ "SkyeChip" },
		{/*  35, 0x23, */ "Guangzhou Kaishile Trading Co Ltd" },
		{/*  36, 0xA4, */ "Jing Pai Digital Technology (Shenzhen) Co" },
		{/*  37, 0x25, */ "Memoritek" },
		{/*  38, 0x26, */ "Zhejiang Hikstor Technology Co Ltd" },
		{/*  39, 0xA7, */ "Memoritek PTE Ltd" },
		{/*  40, 0xA8, */ "Longsailing Semiconductor Co Ltd" },
		{/*  41, 0x29, */ "LX Semicon" },
		{/*  42, 0x2A, */ "Shenzhen Techwinsemi Technology Co Ltd" },
		{/*  43, 0xAB, */ "AOC" },
		{/*  44, 0x2C, */ "GOEPEL Electronic GmbH" },
		{/*  45, 0xAD, */ "Shenzhen G-Bong Technology Co Ltd" },
		{/*  46, 0xAE, */ "Openedges Technology Inc" },
		{/*  47, 0x2F, */ "EA Semi Shangahi Limited" },
		{/*  48, 0xB0, */ "EMBCORF" },
		{/*  49, 0x31, */ "Shenzhen MicroBT Electronics Technology" },
		{/*  50, 0x32, */ "Shanghai Simor Chip Semiconductor Co" },
		{/*  51, 0xB3, */ "Xllbyte" },
		{/*  52, 0x34, */ "Guangzhou Maidite Electronics Co Ltd." },
		{/*  53, 0xB5, */ "Zhejiang Changchun Technology Co Ltd" },
		{/*  54, 0xB6, */ "Beijing Cloud Security Technology Co Ltd" },
		{/*  55, 0x37, */ "SSTC Technology and Distribution Inc" },
		{/*  56, 0x38, */ "Shenzhen Panmin Technology Co Ltd" },
		{/*  57, 0xB9, */ "ITE Tech Inc" },
		{/*  58, 0xBA, */ "Beijing Zettastone Technology Co Ltd" },
		{/*  59, 0x3B, */ "Powerchip Micro Device" },
		{/*  60, 0xBC, */ "Shenzhen Ysemi Computing Co Ltd" },
		{/*  61, 0x3D, */ "Shenzhen Titan Micro Electronics Co Ltd" },
		{/*  62, 0x3E, */ "Shenzhen Macroflash Technology Co Ltd" },
		{/*  63, 0xBF, */ "Advantech Group" },
		{/*  64, 0x40, */ "Shenzhen Xingjiachen Electronics Co Ltd" },
		{/*  65, 0xC1, */ "CHUQI" },
		{/*  66, 0xC2, */ "Dongguan Liesun Trading Co Ltd" },
		{/*  67, 0x43, */ "Shenzhen Miuman Technology Co Ltd" },
		{/*  68, 0xC4, */ "Shenzhen Techwinsemi Technology Twsc" },
		{/*  69, 0x45, */ "Encharge AI Inc" },
		{/*  70, 0x46, */ "Shenzhen Zhenchuang Electronics Co Ltd" },
		{/*  71, 0xC7, */ "Giant Chip Co. Ltd" },
		{/*  72, 0xC8, */ "Shenzhen Runner Semiconductor Co Ltd" },
		{/*  73, 0x49, */ "Scalinx" },
		{/*  74, 0x4A, */ "Shenzhen Lanqi Electronics Co Ltd" },
		{/*  75, 0xCB, */ "CoreComm Technology Co Ltd" },
		{/*  76, 0x4C, */ "DLI Memory" },
		{/*  77, 0xCD, */ "Shenzhen Fidat Technology Co Ltd" },
		{/*  78, 0xCE, */ "Hubei Yangtze Mason Semiconductor Tech" },
		{/*  79, 0x4F, */ "Flastor" },
		{/*  80, 0xD0, */ "PIRATEMAN" },
		{/*  81, 0x51, */ "Barrie Technologies Co Ltd" },
		{/*  82, 0x52, */ "Dynacard Co Ltd" },
		{/*  83, 0xD3, */ "Rivian Automotive" },
		{/*  84, 0x54, */ "Shenzhen Fidat Technology Co Ltd" },
		{/*  85, 0xD5, */ "Zhejang Weiming Semiconductor Co Ltd" },
		{/*  86, 0xD6, */ "Shenzhen Xinhua Micro Technology Co Ltd" },
		{/*  87, 0x57, */ "Duvonn Electronic Technology Co Ltd" },
		{/*  88, 0x58, */ "Shenzhen Xinchang Technology Co Ltd" },
		{/*  89, 0xD9, */ "Leidos" },
		{/*  90, 0xDA, */ "Keepixo" },
		{/*  91, 0x5B, */ "Applied Brain Research Inc" },
		{/*  92, 0xDC, */ "Maxio Technology (Hangzhou) Co Ltd" },
		{/*  93, 0x5D, */ "HK DCHIP Technology Limited" },
		{/*  94, 0x5E, */ "Hitachi-LG Data Storage" },
		{/*  95, 0xDF, */ "Shenzhen Huadian Communication Co Ltd" },
		{/*  96, 0xE0, */ "Achieve Memory Technology (Suzhou) Co" },
		{/*  97, 0x61, */ "Shenzhen Think Future Semiconductor Co" },
		{/*  98, 0x62, */ "Innosilicon" },
		{/*  99, 0xE3, */ "Shenzhen Weilida Technology Co Ltd" },
		{/* 100, 0x64, */ "Agrade Storage (Shenzhen) Co Ltd" },
		{/* 101, 0xE5, */ "Shenzhen Worldshine Data Technology Co" },
		{/* 102, 0xE6, */ "Mindgrove Technologies" },
		{/* 103, 0x67, */ "BYD Semiconductor Co Ltd" },
		{/* 104, 0x68, */ "Chipsine Semiconductor (Suzhou) Co Ltd" },
		{/* 105, 0xE9, */ "Shen Zhen Shi Xun He Shi Ji Dian Zi You" },
		{/* 106, 0xEA, */ "Shenzhen Jindacheng Computer Co Ltd" },
		{/* 107, 0x6B, */ "Shenzhen Baina Haichuan Technology Co" },
		{/* 108, 0xEC, */ "Shanghai Hengshi Electronic Technology" },
		{/* 109, 0x6D, */ "Beijing Boyu Tuxian Technology Co Ltd" },
		{/* 110, 0x6E, */ "China Chips Star Semiconductor Co Ltd" },
		{/* 111, 0xEF, */ "Shenzhen Shenghuacan Technology Co" },
		{/* 112, 0x70, */ "Kinara Inc" },
		{/* 113, 0xF1, */ "TRASNA Semiconductor" },
		{/* 114, 0xF2, */ "KEYSOM" },
		{/* 115, 0x73, */ "Shenzhen YYF Info Tech Co Ltd" },
		{/* 116, 0xF4, */ "Sharetronics Data Technology Co Ltd" },
		{/* 117, 0x75, */ "AptCore Limited" },
		{/* 118, 0x76, */ "Uchampion Semiconductor Co Ltd" },
		{/* 119, 0xF7, */ "YCT Semiconductor" },
		{/* 120, 0xF8, */ "FADU Inc" },
		{/* 121, 0x79, */ "Hefei CLT Microelectronics Co LTD" },
		{/* 122, 0x7A, */ "Smart Technologies(BD) Ltd" },
		{/* 123, 0xFB, */ "Zhangdian District Qunyuan Computer Firm" },
		{/* 124, 0x7C, */ "Silicon Xpandas Electronics Co Ltd" },
		{/* 125, 0xFD, */ "PC Components Y Multimedia S" },
		{/* 126, 0xFE, */ "Shenzhen Tanlr Technology Group Co Ltd"},
	},
	{ // bank #17
		{/*   1, 0x01, */ "Shenzhen JIEQING Technology Co Ltd" },
		{/*   2, 0x02, */ "Orionix" },
		{/*   3, 0x83, */ "JoulWatt Technology Co Ltd" },
		{/*   4, 0x04, */ "Tenstorrent" },
		{/*   5, 0x85, */ "Unis Flash Memory Technology (Chengdu)" },
		{/*   6, 0x86, */ "Huatu Stars" },
		{/*   7, 0x07, */ "Ardor Gaming" },
		{/*   8, 0x08, */ "QuanZhou KunFang Semiconductor Co Ltd" },
		{/*   9, 0x89, */ "EIAI PLANET" },
		{/*  10, 0x8A, */ "Ningbo Lingkai Semiconductor Technology Inc" },
		{/*  11, 0x0B, */ "Shenzhen Hancun Technology Co Ltd" },
		{/*  12, 0x8C, */ "Hongkong Manyi Technology Co Limited" },
		{/*  13, 0x0D, */ "Shenzhen Storgon Technology Co Ltd" },
		{/*  14, 0x0E, */ "YUNTU Microelectronics" },
		{/*  15, 0x8F, */ "Essencore" },
		{/*  16, 0x10, */ "Shenzhen Xingyun Lianchuang Computer Tech" },
		{/*  17, 0x91, */ "ShenZhen Aoscar Digital Tech Co Ltd" },
		{/*  18, 0x92, */ "XOC Technologies Inc" },
		{/*  19, 0x13, */ "BOS Semiconductors" },
		{/*  20, 0x94, */ "Eliyan Corp" },
		{/*  21, 0x15, */ "Hangzhou Lishu Technology Co Ltd" },
		{/*  22, 0x16, */ "Tier IV Inc" },
		{/*  23, 0x97, */ "Wuhan Xuanluzhe Network Technology Co" },
		{/*  24, 0x98, */ "EA Semi (Shanghai) Limited" },
		{/*  25, 0x19, */ "Tech Vision Information Technology Co" },
		{/*  26, 0x1A, */ "Zhihe Computing Technology" },
		{/*  27, 0x9B, */ "Beijing Apexichips Tech" },
		{/*  28, 0x1C, */ "Yemas Holdingsl Limited" },
		{/*  29, 0x9D, */ "Eluktronics" },
		{/*  30, 0x9E, */ "Walton Digi-Tech Industries Ltd" },
		{/*  31, 0x1F, */ "Beijing Qixin Gongli Technology Co Ltd" },
		{/*  32, 0x20, */ "M.RED" },
		{/*  33, 0xA1, */ "Shenzhen Damay Semiconductor Co Ltd" },
		{/*  34, 0xA2, */ "Corelab Tech Singapore Holding PTE LTD" },
		{/*  35, 0x23, */ "EmBestor Technology Inc" },
		{/*  36, 0xA4, */ "XConn Technologies" },
		{/*  37, 0x25, */ "Flagchip" },
		{/*  38, 0x26, */ "CUNNUC" },
		{/*  39, 0xA7, */ "SGMicro" },
		{/*  40, 0xA8, */ "Lanxin Computing (Shenzhen) Technology" },
		{/*  41, 0x29, */ "FuturePlus Systems LLC" },
		{/*  42, 0x2A, */ "Shenzhen Jielong Storage Technology Co" },
		{/*  43, 0xAB, */ "Precision Planting LLC" },
		{/*  44, 0x2C, */ "Sichuan ZeroneStor Microelectronics Tech" },
		{/*  45, 0xAD, */ "The University of Tokyo" },
		{/*  46, 0xAE, */ "Aodu (Fujian) Information Technology Co" },
		{/*  47, 0x2F, */ "Bytera Memory Inc" },
		{/*  48, 0xB0, */ "XSemitron Technology Inc" },
		{/*  49, 0x31, */ "Cloud Ridge Ltd" },
		{/*  50, 0x32, */ "Shenzhen XinChiTai Technology Co Ltd" },
		{/*  51, 0xB3, */ "Shenzhen Xinxin Semiconductor Co Ltd" },
		{/*  52, 0x34, */ "Shenzhen ShineKing Electronics Co Ltd." },
		{/*  53, 0xB5, */ "Shenzhen Shande Semiconductor Co. Ltd." },
		{/*  54, 0xB6, */ "AheadComputing" },
		{/*  55, 0x37, */ "Beijing Ronghua Kangweiye Technology" },
		{/*  56, 0x38, */ "Shanghai Yunsilicon Technology Co Ltd" },
		{/*  57, 0xB9, */ "Shenzhen Wolongtai Technology Co Ltd." },
		{/*  58, 0xBA, */ "Vervesemi Microelectronics" },
		// ...
	},
};
