/*	Benjamin DELPY `gentilkiwi`
	https://blog.gentilkiwi.com
	benjamin@gentilkiwi.com
	Licence : https://creativecommons.org/licenses/by/4.0/
*/
/* * * * * * * * * * * * * * * * * * * * * * * * *
 * Atmel
 * -----------------------------------------------
 * Atmel
 * Microchip
 * Adesto
 * Renesas
 * ...
 * * * * * * * * * * * * * * * * * * * * * * * * */
#pragma once
#include "../kiflashrom.h"

#define AT45DB_JEDEC_BANK			1
#define AT45DB_JEDEC_MANUFACTURER	31

#define AT45DB_OPCODE_MAIN_MEMORY_PAGE_LEGACY			0xd2
#define AT45DB_OPCODE_CONTINUOUS_ARRAY_READ_LEGACY		0xe8
#define AT45DB_OPCODE_CONTINUOUS_ARRAY_READ_LOW_FREQ	0x03 // GENERIC_OPCODE_READ_DATA
#define AT45DB_OPCODE_CONTINUOUS_ARRAY_READ_HIGH_FREQ	0x0b // GENERIC_OPCODE_FAST_READ
#define AT45DB_OPCODE_BUFFER_1_READ_LOW_FREQ			0xd1
#define AT45DB_OPCODE_BUFFER_2_READ_LOW_FREQ			0xd3
#define AT45DB_OPCODE_BUFFER_1_READ						0xd4
#define AT45DB_OPCODE_BUFFER_2_READ						0xd6

#define AT45DB_OPCODE_BUFFER_1_WRITE					0x84
#define AT45DB_OPCODE_BUFFER_2_WRITE					0x87
#define AT45DB_OPCODE_BUFFER_1_TO_MAIN_MEMORY_PAGE_PROGRAM_WITH_ERASE	0x83
#define AT45DB_OPCODE_BUFFER_2_TO_MAIN_MEMORY_PAGE_PROGRAM_WITH_ERASE	0x86
#define AT45DB_OPCODE_BUFFER_1_TO_MAIN_MEMORY_PAGE_PROGRAM_NO_ERASE		0x88
#define AT45DB_OPCODE_BUFFER_2_TO_MAIN_MEMORY_PAGE_PROGRAM_NO_ERASE		0x89
#define AT45DB_OPCODE_PAGE_ERASE						0x81
#define AT45DB_OPCODE_BLOCK_ERASE						0x50
#define AT45DB_OPCODE_SECTOR_ERASE						0x7c
#define AT45DB_OPCODE_CHIP_ERASE						0xc7, 0x94, 0x80, 0x9a
#define AT45DB_OPCODE_MAIN_MEMORY_PAGE_PROGRAM_THROUGH_BUFFER_1			0x82
#define AT45DB_OPCODE_MAIN_MEMORY_PAGE_PROGRAM_THROUGH_BUFFER_2			0x85

#define AT45DB_OPCODE_ENABLE_SECTOR_PROTECTION			0x3d, 0x2a, 0x7f, 0xa9
#define AT45DB_OPCODE_DISABLE_SECTOR_PROTECTION			0x3d, 0x2a, 0x7f, 0x9a
#define AT45DB_OPCODE_ERASE_SECTOR_PROTECTION_REG		0x3d, 0x2a, 0x7f, 0xcf
#define AT45DB_OPCODE_PROGRAM_SECTOR_PROTECTION_REG		0x3d, 0x2a, 0x7f, 0xfc
#define AT45DB_OPCODE_READ_SECTOR_PROTECTION_REG		0x32
#define AT45DB_OPCODE_SECTOR_LOCKDOWN					0x3d, 0x2a, 0x7f, 0x30
#define AT45DB_OPCODE_READ_SECTOR_LOCKDOWN_REG			0x35
#define AT45DB_OPCODE_PROGRAM_SECURITY_REG				0x9b, 0x00, 0x00, 0x00
#define AT45DB_OPCODE_READ_SECURITY_REG					0x77

#define AT45DB_OPCODE_MAIN_MEMORY_PAGE_TO_BUFFER_1_TRANSFER	0x53
#define AT45DB_OPCODE_MAIN_MEMORY_PAGE_TO_BUFFER_2_TRANSFER	0x55
#define AT45DB_OPCODE_MAIN_MEMORY_PAGE_TO_BUFFER_1_COMPARE	0x60
#define AT45DB_OPCODE_MAIN_MEMORY_PAGE_TO_BUFFER_2_COMPARE	0x61
#define AT45DB_OPCODE_AUTO_PAGE_REWRITE_THROUGH_BUFFER_1	0x58
#define AT45DB_OPCODE_AUTO_PAGE_REWRITE_THROUGH_BUFFER_2	0x59
#define AT45DB_OPCODE_DEEP_POWER_DOWN						0xb9
#define AT45DB_OPCODE_RESUME_FROM_DEEP_POWER_DOWN			0xab
#define AT45DB_OPCODE_STATUS_REGISTER_READ					0xd7
#define AT45DB_OPCODE_MANUFACTURER_AND_DEVICE_ID_READ		0x9f
// Legacy
#define AT45DB_OPCODE_LEGACY_BUFFER_1_READ					0x54
#define AT45DB_OPCODE_LEGACY_BUFFER_2_READ					0x56
#define AT45DB_OPCODE_LEGACY_MAIN_MEMORY_PAGE_READ			0x52
#define AT45DB_OPCODE_LEGACY_CONTINUOUS_ARRAY_READ			0x68
#define AT45DB_OPCODE_LEGACY_STATUS_REGISTER_READ			0x57

/* AT45DB
 * -----------------------------------------------
 * AT45DB081  \
 * AT45DB081A  - no Device ID
 * AT45DB081B /
 * AT45DB081D 
 * AT45DB081E - EDI to 1, new opcodes
 */

#define UID_AT45DB041	MAKE_CHIP_UID(AT45DB_JEDEC_BANK, AT45DB_JEDEC_MANUFACTURER, 0x24, 0x00)
#define UID_AT45DB081	MAKE_CHIP_UID(AT45DB_JEDEC_BANK, AT45DB_JEDEC_MANUFACTURER, 0x25, 0x00)
#define UID_AT45DB161	MAKE_CHIP_UID(AT45DB_JEDEC_BANK, AT45DB_JEDEC_MANUFACTURER, 0x26, 0x00)

#define AT45DB_Read_Status(handle, pStatus)		Generic_Read_Byte(handle, AT45DB_OPCODE_STATUS_REGISTER_READ, pStatus)
FT_STATUS AT45DB_Read_ID_EDI(FT_HANDLE handle, BYTE* cbEDI, BYTE** ppbEDI);
